LogIn만들기🐶
CodeSoom/react-week7-assignment-1 pull request #37
Opened 2021-03-08 10:17 UTC by shinhyogeun

강의 시간이 기네요! 일단은 시청하고 처음부터 작성해보고 있어요.

오늘은 많은 양을 할 수 없을 것같아서 일단은 PR를 보냅니다!

감사합니다😊

2021-03-08 13:10 UTC, Kihyun92 requested changes
빠른 PR 좋습니다~~ 이번주도 화이팅입니다 ㅎㅎ

2021-03-08 13:10 UTC, Kihyun92 commented on src/pages/LoginPage/LoginForm.jsx
> +  const { email, password } = userLoginInputs;
```suggestion
export default function LoginForm({ email, password, onChange, onSubmit }) {
```
userLoginInputs 자체로는 사용되지 않고, 구조분해할당하여 사용하는 것 같아요. 

애초에 각각 넘겨주는 방식도 괜찮을 것 같네요~

2021-03-09 01:08 UTC, shinhyogeun commented on src/pages/LoginPage/LoginForm.jsx
> +  const { email, password } = userLoginInputs;
로그인폼에 인자가 많아지는 것 같아서 관련된 것은 useLoginInputs으로 두었습니다. 
state에서 둘은 같이 있어서 가독성도 좋아보이는데 분해해서 해야할까요..?

2021-03-09 11:59 UTC, shinhyogeun commented
오늘은 login을 구현하고 리뷰작성 폼과 리스트를 만들었습니다. 물론 강의를 그대로 따라하지 않아서 조금 다를 수 있는데 일단은 구현 후 리팩토링을 할 예정입니다~😊

<img width="614" alt="스크린샷 2021-03-09 오후 8 50 32" src="https://user-images.githubusercontent.com/52554235/110466394-19af0c80-8119-11eb-974f-7b330ef5ef02.png">

질문이 하나 있습니다!! 위의 test에서 MemoryRouter안에 RestaurantPage가 있습니다.
그런데 MemoryRouter안에서 initialEntries의 restaurants 뒤의 숫자 1을 어떻게 RestaurantPage가 params로 인지하는지 궁금합니다..
저희는 분명 App에서 `<Route path="/restaurants/:id" component={RestaurantPage} />`를 사용했습니다

그런데 MemoryRouter안의 RestaurantPage가 위의 코드를 알수 있나요?

```
<MemoryRouter initialEntries={[path]}>
        <Route
          path="./restaurants/:id"
          component={RestaurantsDetailPage}
        />
</MemoryRouter>
```

위에처럼 써야지 id가 params인 것을 알 수 있는 것 아닌가요? 🤔🤔

감사합니다~👍

2021-03-09 13:00 UTC, Kihyun92 commented on src/pages/LoginPage/LoginForm.jsx
> +  const { email, password } = userLoginInputs;
말씀하신 이유라면 지금도 괜찮을 것 같습니다~ 😊

개인적으로 `userLoginInputs`이라는 객체명이 명확하지 않아 보이기도하고 이런 상황에는 구조분해 할당을 해서 넘기는걸 선호해서 커맨트 드렸습니다 ㅎㅎ

2021-03-09 13:23 UTC, Kihyun92 commented
> <img alt="스크린샷 2021-03-09 오후 8 50 32" width="614" src="https://user-images.githubusercontent.com/52554235/110466394-19af0c80-8119-11eb-974f-7b330ef5ef02.png">
> 
> 질문이 하나 있습니다!! 위의 test에서 MemoryRouter안에 RestaurantPage가 있습니다.
> 그런데 MemoryRouter안에서 initialEntries의 restaurants 뒤의 숫자 1을 어떻게 RestaurantPage가 params로 인지하는지 궁금합니다..
> 저희는 분명 App에서 `<Route path="/restaurants/:id" component={RestaurantPage} />`를 사용했습니다
> 
> 그런데 MemoryRouter안의 RestaurantPage가 위의 코드를 알수 있나요?
> 
> ```
> <MemoryRouter initialEntries={[path]}>
>         <Route
>           path="./restaurants/:id"
>           component={RestaurantsDetailPage}
>         />
> </MemoryRouter>
> ```
> 
> 위에처럼 써야지 id가 params인 것을 알 수 있는 것 아닌가요? 🤔🤔

코드를 보니 실제

2021-03-09 13:33 UTC, Kihyun92 requested changes

2021-03-09 13:33 UTC, Kihyun92 commented on src/pages/RestaurantPage/ReviewForm.jsx
> +  const { score, description } = userReviewInputs;
`userReviewInputs` 보다는 조금 단순히 `review`는 어떤가요?

2021-03-10 10:58 UTC, shinhyogeun commented on src/pages/LoginPage/LoginForm.jsx
> +  const { email, password } = userLoginInputs;
아 제가 잘못 봤었어요.. 저는 initialState를 각각 따로 분리하라고 말씀하신줄 알았습니다. 수정할게요!😊

2021-03-10 10:59 UTC, shinhyogeun commented on src/pages/RestaurantPage/ReviewForm.jsx
> +  const { score, description } = userReviewInputs;
넵 수정하겠습니다~!😊

2021-03-10 11:02 UTC, shinhyogeun commented
너무 어려워서.. 천천히 진행하고 있어요.. 😭😭😭😭
쉽게 시간이 나지를 않네요.. 침착하게 진행하면 좋으련만 시간이 없어서 눈에 더 안들어오게되네요ㅠㅠ

슬랙에도 남겼지만 헷갈려서요..
리뷰를 작성하고 리뷰남기기 버튼을 누르면 바로 밑에 자기가 쓴 리뷰가 보입니다.
기존에 있던 리뷰 앞에 제가 쓴 리뷰가 들어가게 됩니다.
`[방금작성한리뷰, 원래리뷰1, 원래리뷰2, …, 원래리뷰n]`
이런식으로 되는데 새로고침해도 이렇게 보이게 하면 되나요?
아니면 새로고침하면 `[원래리뷰1, 원래리뷰2, …, 원래리뷰n, 방금작성한리뷰]` 이렇게 바뀌게 되어도 괜찮은가요? 
 헷갈려서 여쭤봅니다~!🤔

항상 코드리뷰에서 많은 도움을 받고있습니다😊👍

2021-03-10 14:43 UTC, Kihyun92 commented
> 너무 어려워서.. 천천히 진행하고 있어요.. 😭😭😭😭
> 쉽게 시간이 나지를 않네요.. 침착하게 진행하면 좋으련만 시간이 없어서 눈에 더 안들어오게되네요ㅠㅠ
> 
> 슬랙에도 남겼지만 여기에도 한번 더 남겨볼게요!
> 
> 리뷰를 작성하고 리뷰남기기 버튼을 누르면 바로 밑에 자기가 쓴 리뷰가 보입니다.
> 기존에 있던 리뷰 앞에 제가 쓴 리뷰가 들어가게 됩니다.
> `[방금작성한리뷰, 원래리뷰1, 원래리뷰2, …, 원래리뷰n]`
> 이런식으로 되는데 새로고침해도 이렇게 보이게 하면 되나요?
> 아니면 새로고침하면 `[원래리뷰1, 원래리뷰2, …, 원래리뷰n, 방금작성한리뷰]` 이렇게 바뀌게 되어도 괜찮은가요?
> 헷갈려서 여쭤봅니다~!🤔
> 
> 이게 리뷰를 post로 추가하면 기존 리뷰배열 뒤에 넣더라구요 그런데 과제 시연영상에서는 작성하면 맨 위에 오게됩니다.
> 리뷰를 post하는 것을 성공하면 state에 있는 review배열에는 앞에 끼워넣는것을 원하시는 건지 헷갈리네요🤔
> (이럴경우 새로고침하면 다시 리뷰를 불러오기 때문에 썼던 리뷰는 맨 뒤로 가게 됩니다!)
> 
> 항상 해주시는 코드리뷰에서 많은 도움을 받고있습니다 감사합니다!😊👍

너무 조급해마시고 조금씩 꾸준히 해보시면 좋을 것 같아요! 👍🏼  효근님 충분히 잘 하고 계십니다 ㅎㅎ

과제에 리뷰 순서 관련해서 제한사항은 없지만, 관련해서 고민해보시고 동료들과 의논해본게 너무 좋네요! 💯 

실제로 리스트를 구현할때 정렬 순서는 항상 고려되는 부분이죠. 오름차순이던 내림차순이던 본인의 기준에 맞게 구현해보시면 좋을 것 같습니다.

잘못됐거나 의논이 필요한 부분이 있다면 언제든 말씀주세요!

2021-03-10 15:03 UTC, Kihyun92 requested changes

2021-03-11 07:43 UTC, shinhyogeun commented on src/pages/LoginPage/LoginFormContainer.jsx
> +  }
그렇네요! 항상 다른 분들을 생각하면서 코드를 짜야겠네요!👍

2021-03-11 07:53 UTC, shinhyogeun commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessToken('ACCESS_TOKEN'));
`setAccessToken('ACCESS_TOKEN')` 이것을 
```
{
    type: 'setAccessToken',
    payload: { accessToken: 'ACCESS_TOKEN },
}
```

다음과 같은 형식으로 바꿨습니다 감사합니다!

2021-03-11 11:27 UTC, shinhyogeun commented
로컬스토리지 부분을 아직 하지 못해서 e2e가 깨지는 것같습니다! 그리고 구조도 상당히 복잡하게되었습니다. 
아샬님은 입력폼을 하나 만드셔서 사용하지만 저는 그 부분을 아직 리팩토링하지 못했습니다.
내일은 로컬스토리지를 이용하여 마저 완성하고싶습니다! 

```
export function loadRestaurant({ restaurantId }) {
  return async (dispatch, getState) => {
    if (getState()?.restaurant?.id !== Number(restaurantId)) {
      dispatch(setRestaurant(null));
    }

    const restaurant = await fetchRestaurant({ restaurantId });

    dispatch(setRestaurant(restaurant));
  };
}
```

리뷰를 post하면 loadRestaurant가 실행되면서 기존 레스토랑정보를 버리고 다시 가져옵니다. 
하지만 이 과정에서 loading글자가 다시나와서 사용자 경험이 별로인 것같아서
`if (getState()?.restaurant?.id !== Number(restaurantId))`
위의 코드로 지금 로드하는 레스토랑이 새로운 레스토랑인지를 확인해보려고 했습니다. 
하지만 초깃값때문에 옵셔널 체이닝까지 써버려서 좀.. 이상해 보이는데 이것을 깔끔하게 바꿀 수 있나요?
그냥 if안에를 새로운 함수 _isNewRestaurant_ 라는 함수로 만드는 것은 어떤가요?

2021-03-11 14:58 UTC, Kihyun92 requested changes
만약 의도하신대로라면 말씀하신대로 if 내부 조건문을 따로 추상화 해주는게 좋을 것 같아요 :)

실제 현업에서도 리스트에 등록 이후에 로딩 처리를 어떻게 할지 많이 고민하는 부분입니다 ㅎㅎ

만약 로딩이 노출되면 안될 경우엔 일단 기존에 받아온 리스트에 삽입하여 노출하는 방식(리스트를 새로 로딩하지 않음)을 적용하는 방법도 사용합니다만, 대부분은 단순하게 등록 이후에 새로 리스트를 받아오는걸 표현하기 위해 로딩을 적절하게 넣어주기도 하는것 같아요  😊

2021-03-11 14:58 UTC, Kihyun92 commented on src/pages/LoginPage/LoginFormContainer.jsx
> +    dispatch(resetLoginInput());
하나의 액션에서 처리해주는 것도 괜찮을 것 같군요~

2021-03-11 14:58 UTC, Kihyun92 commented on src/pages/LoginPage/LoginFormContainer.jsx
> +      <p>{accessToken}</p>
확인을 위해 화면에 노출하는 건가요? 🤔

2021-03-11 14:58 UTC, Kihyun92 commented on src/pages/LoginPage/LoginFormContainer.jsx
> +      </button>
로직이 단순하지만, LoginForm처럼 컴포넌트로 분리해서 처리해줘도 좋을것 같네요 :)

2021-03-11 14:58 UTC, Kihyun92 commented on src/pages/RestaurantPage/RestaurantContainer.jsx
> +    dispatch(resetReviewInput());
이 부분도 리셋해주는 부분을 따로 디스패치하는것도 좋지만,, sendReview에서 함께 처리해주는건 어떤가요?

2021-03-11 14:58 UTC, Kihyun92 commented on src/pages/RestaurantPage/RestaurantContainer.jsx
> +      ) : null}
삼항연산자 대신 이렇게 사용할 수도 있겠네요~ 

다만 항상 이 경우엔 체크하는 값이 0이 되지 않는지 확인을 해줘야합니다. 화면에 0이 노출되지 않도록 말이죠 ㅎㅎ
```suggestion
      {accessToken && (
        <ReviewForm
          review={review}
          onChange={handleChange}
          onSubmit={handleSubmit}
        />
      )}
```

2021-03-12 03:58 UTC, shinhyogeun commented on src/pages/LoginPage/LoginFormContainer.jsx
> +    dispatch(resetLoginInput());
그렇네요!! 합치겠습니다!👍

2021-03-12 03:59 UTC, shinhyogeun commented on src/pages/LoginPage/LoginFormContainer.jsx
> +      <p>{accessToken}</p>
제가 실수로 이 부분을 확인차 했던 것이 끝난 후에 제거하는 것을 깜빡했네요! 지웠습니다!

2021-03-12 03:59 UTC, shinhyogeun commented on src/pages/LoginPage/LoginFormContainer.jsx
> +      </button>
LogoutButton으로 분리했습니다!!!

2021-03-12 04:02 UTC, shinhyogeun commented on src/pages/RestaurantPage/RestaurantContainer.jsx
> +    dispatch(resetReviewInput());
처음에 이것을 안에 넣을까 밖으로 꺼낼까 고민을 많이 했었어요!!
결국 뺐지만 .. ㅎㅎ😭 넣는게 더 좋아보여요!!
관심사도 관심사지만 이렇게 빼면 화면에서 바뀌는게 살짝어색하더라구요. 
뭔가 제 리뷰를 포스트하기 전에 제 입력들이 다 사라진느낌이라서..🤔 sendReview에서 함께 처리해주겠습니다!

2021-03-12 04:11 UTC, shinhyogeun commented on src/pages/RestaurantPage/RestaurantContainer.jsx
> +      ) : null}
보여주신 걸로 바꿨습니다(JS 코딩의 기술에서도 이 부분이 있어서 기억이 나네요!)

accessToken이 0일 경우에도 (그럴 일은 없지만..) 그려져야하는 경우는 밑에처럼 삼항연산자와 단락평가를 같이 해서 표현할 수 있겠네요!

```
accessToken && accessToken === 0 ?  (
      <ReviewForm
        review={review}
        onChange={handleChange}
        onSubmit={handleSubmit}
      />
    ) : null
```

2021-03-12 11:49 UTC, shinhyogeun commented
로그아웃이 되었을 때 localStorage의 accessToken을 초기화 하는 것을 아직 하지않았습니다! 내일 할게요..ㅠㅠ😭😭😭

2021-03-12 15:53 UTC, Kihyun92 requested changes

2021-03-12 15:53 UTC, Kihyun92 commented on src/actions.js
> +    if (isNewRestaurant(id, newId)) {
```suggestion
    const { id } = getState()?.restaurant;

    if (id && isNewRestaurant(id, restaurantId)) {
```

한번 더 추상화 해줄 필요 없이 위와 같이 처리해도 좋겠네요.

그리고 isNewRestaurant가 다른 컴포넌트에서 재사용 되는 경우가 아니라면 굳이 util 쪽에 선언하지 않고 현재 파일의 상단에 선언해줘도 좋겠네요 :)

2021-03-12 17:29 UTC, shinhyogeun commented
로그아웃할 때 localStorage의 'accessToken'을 공백으로 바꾸려는 것을 할 때 저는 처음에 logout버튼을 눌렀을 때 일어나는 handleClick함수 내부에
```
dispatch(resetAccessToken());
saveItme('accessToken','');
```
위에처럼 했을 경우 saveItem이 실행이 안되었습니다.. 그리고 테스트는 saveItem을 모른다고 했습니다.
그래서 dispatch를 다음처럼 바꾸니 정상 작동합니다..ㅠㅠ 이유를 모르겟습니다..
```
export function resetLogin() {
  return async (dispatch) => {
    saveItem('accessToken', '');

    dispatch(resetAccessToken());
  };
}
```
 혹시 알려주실 수 있을 까요? 왜 첫번째 코드처럼 쓴다면 saveItem이 실행이 안되는걸까요..?
비동기 관련 무엇인가 순서가 꼬이는 느낌이라 saveItem을 파악하지 못하는 것같은데 정확하게는 느껴지지 않네요ㅠㅠ

2021-03-13 14:54 UTC, Kihyun92 commented
> 로그아웃할 때 localStorage의 'accessToken'을 공백으로 바꾸려는 것을 할 때 저는 처음에 logout버튼을 눌렀을 때 일어나는 handleClick함수 내부에
> 
> ```
> dispatch(resetAccessToken());
> saveItem('accessToken','');
> ```
> 
> 위에처럼 했을 경우 saveItem이 실행이 안되었습니다.. 그리고 테스트는 saveItem을 모른다고 했습니다.
> 그래서 dispatch를 다음처럼 바꾸니 정상 작동합니다..ㅠㅠ 이유를 모르겟습니다..
> 
> ```
> export function resetLogin() {
>   return async (dispatch) => {
>     saveItem('accessToken', '');
> 
>     dispatch(resetAccessToken());
>   };
> }
> ```
> 
> 혹시 알려주실 수 있을 까요? 왜 첫번째 코드처럼 쓴다면 saveItem이 실행이 안되는걸까요..?
> 비동기 관련 무엇인가 순서가 꼬이는 느낌이라 saveItem을 파악하지 못하는 것같은데 정확하게는 느껴지지 않네요ㅠㅠ

음 당시의 코드를 정확히 모르기 때문에 답변드리기 쉽지 않네요..

LoginFormContainer.jsx의 handleLogout에서 아래 코드를 적용해보셨다는 말이죠?
```
  dispatch(resetAccessToken());
  saveItem('accessToken','');
```

실행이 안된걸 엑세스 토큰 유무로 판단하신걸까요?

테스트에서는 saveItem을 올바르게 사용하셨나요? 관련해서 제가 확인해볼 수 있는 커밋이 있을까요??

유추하기로는 말씀하신대로 비동기 처리로 인해 다른 사이드 이펙트가 발생한 것 같기도 합니다.

2021-03-13 15:02 UTC, Kihyun92 requested changes

2021-03-13 15:02 UTC, Kihyun92 commented on src/services/storage.js
> +  }
이 처리는 API 응답에서 엑세스 토큰이 넘어오지 않는 경우를 위함인가요?

그렇다면 API를 fetch 해올때 accessToken이 있는 경우에만 saveItem을 해주도록 예외처리 하는건 어떨까요?

2021-03-13 15:02 UTC, Kihyun92 commented on src/pages/LoginPage/LoginFormContainer.jsx
> +    dispatch(resetLogin());
`resetLogin`이라는 네이밍이 조금 어색한 것 같아요. 조금 더 의도를 드러내는 네이밍이 좋을 것 같습니다 :)

2021-03-14 05:56 UTC, shinhyogeun commented on src/actions.js
> +    if (isNewRestaurant(id, newId)) {
어제 주신 리뷰를 지금 봣네요 ㅠㅠ 그런데 위에 작성해주신 코드가 정상 작동하나요??
초기에 restaurant에는 id라는 키가 없고.. 126번째 줄도 id가 0이거나 없을때 새로운 아이디인지 확인한다고 쓰신거 같은데 무엇인가 이상한 것같습니다..🤔🤔
(id가 0이 아니면 무조건  if가 통과되어서 `dispatch(setRestaurant(null));`이 실행됩니다..ㅠㅠ)

2021-03-14 05:57 UTC, shinhyogeun commented on src/services/storage.js
> +  }
그게 훨씬 좋은 방법같습니다.. 👍👍 바로 반영하겠습니다.

2021-03-14 07:25 UTC, shinhyogeun commented on src/pages/LoginPage/LoginFormContainer.jsx
> +    dispatch(resetLogin());
logout으로 바꾸었습니다~!!

2021-03-14 07:49 UTC, shinhyogeun commented
> 음 당시의 코드를 정확히 모르기 때문에 답변드리기 쉽지 않네요..
> 
> LoginFormContainer.jsx의 handleLogout에서 아래 코드를 적용해보셨다는 말이죠?
> 
>   dispatch(resetAccessToken());
>   saveItem('accessToken','');
> 실행이 안된걸 엑세스 토큰 유무로 판단하신걸까요?
> 
> 테스트에서는 saveItem을 올바르게 사용하셨나요? 관련해서 제가 확인해볼 수 있는 커밋이 있을까요??
> 
> 유추하기로는 말씀하신대로 비동기 처리로 인해 다른 사이드 이펙트가 발생한 것 같기도 합니다.

다시 시도하니까 정상적으로 작동해요.. 그런데 어제는 정말로 안되어서 제가 logout이라는 액션을 만들면서까지 했었습니다. 안됬던 부분은 로그아웃을 해도 로그아웃이 되지 않았었습니다. 이것에 대한 이유로 저는 `dispatch(resetAccessToken());` -> App을 다시그림 -> accessToken이 로컬스토리지에 있는지 App에서 확인함.(App.jsx의 윗부분) 이과정이 비동기로 이루어지므로 `dispatch(resetAccessToken());`의 다음줄인 `saveItem('accessToken','');`이 실행되기 전에 위에부분이 실행되어 로그아웃이 되어되지 않는 것 같습니다!
그래서 아예 login을 하는 것처럼 순서를 정해서 실행했습니다.

2021-03-14 13:47 UTC, Kihyun92 commented on src/actions.js
> +    if (isNewRestaurant(id, newId)) {
아앗 직접 돌려보지 않고 이런식으로 처리하면 좋겠다고 생각해서 남겼던 커맨트인데 올바르게 동작하지 않는군요 🙇🏻‍♂️

id값을 가져와 처리하는 부분은 뭔가 구조분해할당으로 처리하거나 isNewRestaurant 호출이전에 한번 더 체크해서 조금 더 로직을 단순화 할 수 없을까 싶어서 남겼었던 것 같아요ㅎㅎ;

그리고 `const newId = restaurantId;` 이 부분이 한번 더 추상화해주는 느낌이어서 바로 사용하면 좋을 것 같았습니다.

리뷰드릴 코드량이 많아져서 정신없이 리뷰를 남기다보니 오히려 혼란만 드리는 커맨트를 남긴 것 같네요. 주의하겠습니다 🙏

2021-03-14 13:53 UTC, Kihyun92 approved these changes
쉽지 않은 주 였는데 많이 고민해보시면서 잘 해주신 것 같아요! 이번주도 정말 고생 많으셨습니다~ 👍🏼 

과제 풀이 영상을 한번 보시면서 아샬님은 어떻게 구현하는지 확인해보셔도 좋을 것 같아요~

슬랙 채널에 남겨주신 회고는 잘 봤습니다. 효근님께서 바쁘신 와중에 잘 진행해주셔서 감사하네요 ㅎㅎ 

저도 개인적으로 바쁜 주차여서 제대로 신경써서 리뷰 드리지 못했던것 같아 많이 아쉽습니다 😭

남은 시간도 화이팅 하시죠~ 🔥

2021-05-16 10:08 UTC, merged