리뷰 작성
CodeSoom/react-week7-assignment-1 pull request #39
Opened 2021-03-08 11:00 UTC by HongJungKim-dev

시작합니다!

2021-03-08 12:45 UTC, Kihyun92 commented
이번주도 빠른 PR 좋습니다! 화이팅입니다 :)

2021-03-10 12:34 UTC, HongJungKim-dev commented
강의대로 의도 없이 따라하지않고 최대한 스스로 작은것부터 TDD 진행하려고 노력하고 있습니다.

2021-03-10 14:02 UTC, Kihyun92 commented
> 이번주 과제가 어렵더라도 최대한 작은것부터 TDD 진행하려고 노력하고 있습니다.
> 이제 개인 프로젝트가 다가오다보니 시간이 걸리더라도 의도를 더 생각하면서 해보겠습니다.

조금이라도 꾸준히하는게 중요한 것 같습니다. 꾸준히 잘 진행해주고 계신 것 같아 좋습니다 👍🏼

2021-03-11 11:56 UTC, HongJungKim-dev commented
오늘 학교 과제를 위해 프로그램을 설치하고 삭제하는 과정을 반복해서 시간낭비를 많이해서 코드숨 과제를 많이 하지 못했습니다.

2021-03-11 11:57 UTC, HongJungKim-dev commented on src/LoginForm.test.jsx
> +    expect(handleChange).toBeCalled();
toBeCalledWith으로 시도했는데 오류가 나서 다시 해보려고합니다.

2021-03-11 11:58 UTC, HongJungKim-dev commented on src/LoginForm.test.jsx
> +    expect(handleChange).toBeCalled();
객체를 beforeEach하여 fireEvent.change와 expect작업을 그 내부에서 반복하는것이 하나의 방법인것 같습니다.

2021-03-11 13:35 UTC, Kihyun92 commented on src/reducer.test.js
> +      }));
중복되는 객체는 따로 추출해서 사용해도 좋을 것 같군요!

2021-03-12 11:10 UTC, HongJungKim-dev commented on src/reducer.test.js
> +      }));
수정하겠습니다! 코드를 작성하고 한번이라도 훑어보는 습관을 들여야겠습니다.

2021-03-12 16:42 UTC, Kihyun92 requested changes

2021-03-12 16:42 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  });
현재 이 테스트에서 많은 일을 하는 것 같아보여요. 초기값과 현재 값을 각각 테스트해주는건 어떤가요?

2021-03-12 16:42 UTC, Kihyun92 commented on src/LoginFormContainer.test.jsx
> +    expect(dispatch).toBeCalled();
이메일과 비밀번호를 테스트하는 부분의 로직이 반복 되는 것 같네요!  마찬가지로 재사용 및 확장성 등을 고려하여 개선해주면 좋을 것 같군요

2021-03-13 03:50 UTC, HongJungKim-dev commented on src/LoginForm.test.jsx
> +  });
.

2021-03-13 03:50 UTC, HongJungKim-dev commented on src/LoginFormContainer.test.jsx
> +    expect(dispatch).toBeCalled();
.

2021-03-13 15:10 UTC, Kihyun92 requested changes
차근차근 잘 진행해주고 계신 것 같습니다! 

기능 완성까지 얼마 안남았네요! 💪

2021-03-13 15:10 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessToken(''));
아래 영상을 참고하셔서 액션 객체를 검증하는 방법을 확인해보셔도 좋을 것 같네요 :)

액션 객체 배열 자체를 드러내서 표현하면 무슨 일이 벌어지는지 더 알기 쉬워집니다.

- https://youtu.be/L1dtkLeIz-M?t=2261

2021-03-13 15:10 UTC, Kihyun92 commented on src/reducer.js
> +
불필요한 공백은 제거해주세요~

2021-03-13 15:34 UTC, HongJungKim-dev commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessToken(''));
네 확인해보겠습니다.

2021-03-13 15:35 UTC, HongJungKim-dev commented on src/reducer.js
> +
수정하겠습니다!

2021-03-14 11:32 UTC, HongJungKim-dev commented
마지막까지 최대한 해보려고 과제하다가 아침8시에 5시간 자고 일어나서 더 해보려고 했는데 다 완료하지는 못했습니다. 이번주 코드숨 과제도 어려웠지만 학교강의 및 과제 등이 몰리면서 시간 조절을 잘 못했던것 같습니다. 
다음주면 개인프로젝트 전 마지막 주차인데 마지막 주차 과제 완료하고 못했던것들 다 봐야할것 같습니다.

2021-03-14 13:43 UTC, Kihyun92 approved these changes
바쁜 한 주 였을 것 같아요! 고생하셨습니다 :)

저도 신경써서 피드백을 드리지 못한 것 같아 많이 아쉬운 주차 같네요 😭

과제 풀이 영상을 한번 보시고 아샬님은 어떻게 접근하는지 확인해보시고 남은 부분도 진행해보셔도 좋을 것 같네요~

슬랙 채널에 회고 남겨주시면 머지하도록 하겠습니다~

2021-03-14 13:43 UTC, Kihyun92 commented on src/ReviewForm.jsx
> +export default function ReviewForm({ reviewInputs = initialReviewInputs, onChange, onClick }) {
조금 단순하게 `reviews = initialReviews` 라고만 하는건 어떤가요??

2021-03-14 13:43 UTC, Kihyun92 commented on src/ReviewForm.test.jsx
> +    };
각 테스트들이 모두 같은 초기값을 선언하고 넘겨주고 있는 것 같아요. render 함수에서 기본값으로 처리해주는건 어떨까요?

2021-03-15 15:13 UTC, HongJungKim-dev commented on src/ReviewForm.test.jsx
> +    };
네 그게 더 좋은 방법 인것 같습니다. 수정하겠습니다!

2021-03-15 15:14 UTC, HongJungKim-dev commented on src/ReviewForm.jsx
> +export default function ReviewForm({ reviewInputs = initialReviewInputs, onChange, onClick }) {
다 input을 붙여서 혼동이 올수도 있었던것 같습니다. reviews로 하면 점수와 내용도 포함할 수 있는것 같아서 좋은것 같습니다.

2021-03-22 12:19 UTC, merged