Make login and review
CodeSoom/react-week7-assignment-1 pull request #42
Opened 2021-03-08 12:04 UTC by canary4651

Add base code

2021-03-08 12:46 UTC, Kihyun92 commented
이번주도 화이팅입니다~! :)

2021-03-09 12:56 UTC, Kihyun92 commented
TDD cycle을 잘 지키려 노력해주고 계신 것 같네요 😊

잘 진행해주고 계셔서 아직 리뷰 드릴만한 부분은 보이지 않네요 👍🏼

2021-03-10 13:51 UTC, Kihyun92 requested changes
로그인 필드들을 잘 테스트하며 진행해주고 계신 것 같아요 👍🏼

2021-03-10 13:51 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  });
이 부분은 구현 예정인가요?

2021-03-10 13:51 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('renders "e-mail" input controls', () => {
e-mail 인풋이 그려지는지만 테스트하지 않는 것 같아요. 설명을 추가해주는 건 어떨까요?

2021-03-10 13:51 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('renders login button', () => {
이 부분도 테스트하는 것을 조금 더 설명해줘도 좋겠네요 :)

2021-03-10 13:51 UTC, Kihyun92 commented on src/reducer.test.js
> +      };
중복 로직은 제거해주는게 좋을 것 같네요~

2021-03-10 13:57 UTC, canary4651 commented on src/LoginForm.test.jsx
> +  });
네 구현 예정입니다! 계속 진행하겠습니다!

2021-03-10 13:57 UTC, canary4651 commented on src/LoginForm.test.jsx
> +  it('renders "e-mail" input controls', () => {
테스트 작성할 때 좀 더 신경써서 작성하겠습니다.

2021-03-10 14:15 UTC, canary4651 commented on src/LoginForm.test.jsx
> +  });
앗 다시 보니까 이미 위에서 구현해놨는데 안 지운 거네요... ㅎㅎ 지우겠습니다...!

2021-03-11 13:39 UTC, Kihyun92 requested changes

2021-03-11 13:39 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  });
이메일인지 비밀번호인지만 다를 뿐 동일한 로직이 반복되는 것 같아요~ 

또 다른 인풋이 추가된다면 동일한 로직이 추가될 것 같은데, 중복 로직 제거 및 추후 확장성을 생각한다면 어떻게 해결할 수 있을까요?

2021-03-11 13:39 UTC, Kihyun92 commented on src/reducer.test.js
> +  });
이 부분도 위와 비슷한 경우 같군요!

2021-03-11 13:58 UTC, canary4651 commented on src/LoginForm.test.jsx
> +  });
음....강의에 나온 것처럼 위에서 따로 인풋 값들을 모아서 공통적인 네임을 붙여주고 한번에 테스트하는 식으로 고치면 어떨까요?

2021-03-11 14:05 UTC, canary4651 commented on src/reducer.test.js
> +  });
이부분은 따로 context로 나눌 필요없이 login field로 묶어서 테스트하는 게 좋을까요?

2021-03-12 16:26 UTC, Kihyun92 requested changes

2021-03-12 16:26 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessTocken({}));
아래 영상을 참고하셔서 액션 객체를 검증하는 방법을 확인해보셔도 좋을 것 같네요 :)

액션 객체 배열 자체를 드러내서 표현하면 무슨 일이 벌어지는지 더 알기 쉬워집니다.

- https://youtu.be/L1dtkLeIz-M?t=2261

2021-03-13 14:45 UTC, canary4651 commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessTocken({}));
앗 홀맨님의 발표 영상이군요! 영상 봤었는데,,,,작업을 좀 더 진행해보고 한번 더 리팩터링 하도록 노력할게요!!

2021-03-14 14:38 UTC, Kihyun92 approved these changes
바쁘신 한주였을 텐데 이번주도 고생하셨습니다!

과제 풀이 영상을 한번 보시면서 아샬님은 어떻게 구현하는지 확인해보셔도 좋을 것 같아요ㅎㅎ

슬랙 채널에 회고 남겨주시면 머지하겠습니다! 😊

2021-03-14 14:38 UTC, Kihyun92 commented on src/LogoutForm.test.jsx
> +  });
버튼이 안눌렸을때 호출이 안됐다는걸 따로 context 로 분리해서 확인할 필요는 없을 것 같아요.

```suggestion
    it('calls click event handler when click logout button', () => {
      const { getByText } = renderLogoutForm();

      expect(handleClick).not.toBeCalled();  // 이 부분만으로 버튼이 안눌렸을땐 호출되지 않음을 확인 가능할 것 같아요
      
      fireEvent.click(getByText('Log out'));

      expect(handleClick).toBeCalled();
    });
```

2021-03-14 14:38 UTC, Kihyun92 commented on src/RestaurantContainer.jsx
> +      ) : null}
```suggestion
      {accessToken && (
        <ReviewForm
          fields={reviewFields}
          onChange={handleChange}
          onSubmit={handleSubmit}
        />
      )}
```
accessToken이 0이 되지 않는다면, 조금 더 간단하게 처리해줘도 좋겠네요 :)

(만약 비교하는 값이 0이 된다면 화면에 0이 노출됩니다. 이미 아실 수 있지만, false로 인식될 거라고 생각해서 실수 할 수 있는 부분이죠)

2021-03-14 14:38 UTC, Kihyun92 commented on src/Reviews.jsx
> +  );
부정문으로 예외처리하는건 동료들에게 한번 더 고민하게 만드는 것 같아요. 예외 처리의 순서를 조금 바꾸는건 어떨까요? 

그리고 조금 더 명확하게 처리해줘도 좋겠네요. 아래와 같은 방식은 어떤가요?

```suggestion
  return (
    <>
      <h3>리뷰</h3>
      {reviews && reviews.length > 0 ? (
      <ul>
        {reviews.map(({
          id, name, score, description,
        }) => (
          <li key={id}>
            <div>
              작성자:
              {' '}
              {name}
            </div>
            <div>
              평점:
              {' '}
              {score}
            </div>
            <div>
              리뷰 내용:
              {' '}
              {description}
            </div>
          </li>
        ))}
      </ul>
      ) : (
      <p>
        등록된 리뷰가 없습니다!
      </p>
      )
    </>
  );
```

2021-03-14 14:50 UTC, canary4651 commented on src/LogoutForm.test.jsx
> +  });
일요일까지 리뷰 감사합니다!
오옹 context를 굳이 쓰지 않고 좀 더 간단하게 하는 게 다른 동료들이 읽었을 대 좋은 방식 같네요! 감사합니다 ㅎㅎ

2021-03-14 14:51 UTC, canary4651 commented on src/RestaurantContainer.jsx
> +      ) : null}
오... 그 부분까지는 신경쓰지 못했어요....! 엄청 급하게 하느라..! 
accessToken이 0이 될 일은 없을 거 같으니까 && 로 처리하면 더 간단하네요!

2021-03-14 14:54 UTC, canary4651 commented on src/Reviews.jsx
> +  );
아하!!  생각해보니 회사에서도 작업하면서 부정문보다는 있는 그대로 예외처리를 해주려고 노력하는 데 코드숨 과제에도 적용시켰으면 더 좋았을 거 같네요 ㅎㅎ

2021-03-22 12:17 UTC, merged