🍖 🍙  로그인 & 리뷰 작성
CodeSoom/react-week7-assignment-1 pull request #43
Opened 2021-03-08 12:10 UTC by SangHoonly

첫 PR입니다!

2021-03-08 13:16 UTC, Kihyun92 requested changes
빠른 시작 좋습니다! 이번주도 화이팅하시죠 ㅎㅎ

2021-03-08 13:16 UTC, Kihyun92 commented on src/LoginFormContainer.test.jsx
> +    ));
중복 코드는 함수로 추출해주면 좋겠네요~

2021-03-09 12:33 UTC, Kihyun92 requested changes
차근차근 진행해주고 계신듯하네요! 👍🏼

2021-03-09 12:33 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +    const { getByLabelText } = render(<LoginForm onChange={handleChange} />);
각 테스트별로 확인하고 싶은 함수를 LoginForm 컴포넌트에 넘겨서 테스트해보신 것 같아요~

함수 바깥에 컴포넌트 랜더해주는 함수를 추출하고, 거기에 필요한 props들을(mocking한 handleChange 등) 넘겨주도록 처리하는건 어떨까요? 테스트할때마다 신경이 조금 덜 쓰일 것 같기도 하네요 :)

2021-03-10 12:19 UTC, Kihyun92 commented
아직 새로운 커밋이 없네요😅 혹시 진행하시다가 의논이 필요하다면 편하게 말씀주세요~

2021-03-11 11:54 UTC, SangHoonly commented
![스크린샷 2021-03-11 오후 8 47 00](https://user-images.githubusercontent.com/54464320/110782985-25cad380-82ab-11eb-915e-e3a0ddcee3f8.png)
![스크린샷 2021-03-11 오후 8 50 41](https://user-images.githubusercontent.com/54464320/110783213-7cd0a880-82ab-11eb-80e6-29bc6220320c.png)

강의 내용과 마찬가지로 코드를 작성하였는데, CORS문제에 막혀 access token이 받아지질 않습니다. 그래서 api.js의 postLogin에서 fetch해줄 때 mode: 'no-cors'를 추가하여주었는데, 그럼에도 불구하고 문제가 해결되질 않습니다. 다른 분들께 여쭤 보았더니 다른 분들은 문제가 일어나질 않았고, 코드를 비교해보았더니 코드에서 문제점 또한 보이지 않았는데, 왜 cors문제가 일어났으며, 이 문제를 어떻게 해결해야하는지 모르겠습니다...!!

2021-03-11 15:30 UTC, Kihyun92 commented
url 주소가 잘못된것 같아요!

`로그인: POST https://eatgo-login-api.ahastudio.com/session`

변경해서 한번 해보시겠어요?

2021-03-11 15:40 UTC, Kihyun92 requested changes

2021-03-11 15:40 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('renders "Log In" button', () => {
로그인 버튼이 그려지는만 테스트 하고 있지 않은 것 같아요. 조금 더 설명을 추가해주면 어떨까요? ㅎㅎ

2021-03-12 15:35 UTC, Kihyun92 requested changes

2021-03-12 15:35 UTC, Kihyun92 commented on src/LoginFormContainer.jsx
> +      <p>{accessToken}</p>
확인을 위한 부분 같아요~ 확인이 됐으면 제거해줘도 좋겠네요.

2021-03-12 15:35 UTC, Kihyun92 commented on src/TextField.test.jsx
> +      ));
반복 되는 render 부분도 함수로 추출하면 좋겠네요~

2021-03-12 15:35 UTC, Kihyun92 commented
TextField 추가해보신거 좋네요 👍🏼

2021-03-13 12:23 UTC, SangHoonly commented
일주일동안 과제를 많이 못해서 급하게 달렸습니다...

2021-03-13 12:47 UTC, SangHoonly commented on src/LoginForm.test.jsx
> +  it('renders "Log In" button', () => {
> url 주소가 잘못된것 같아요!
> 
> `로그인: POST https://eatgo-login-api.ahastudio.com/session`
> 
> 변경해서 한번 해보시겠어요?

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ형탁님이랑 같이 할복하기로 했어요

2021-03-13 12:48 UTC, SangHoonly commented
> url 주소가 잘못된것 같아요!
> 
> `로그인: POST https://eatgo-login-api.ahastudio.com/session`
> 
> 변경해서 한번 해보시겠어요?

ㅋㅋㅋㅋㅋㅋㅋㅋ 형탁님이랑 같이 할복하기로 했어요 ㅎㅎ

2021-03-13 14:26 UTC, Kihyun92 requested changes
저도 오타때문에 삽질을 많이하는 편인데 이번엔 발견해서 다행이네요 😂

급하게 하셨다지만 잘 해주신 것 같군요 ㅎㅎ 👍🏼

2021-03-13 14:26 UTC, Kihyun92 commented on src/LoginFormContainer.jsx
> +
불필요한 공백은 제거해주세요~

2021-03-13 14:26 UTC, Kihyun92 commented on src/RestaurantPage.test.jsx
> +    it('renders review write form', () => {
`renders review form` 이라고만 하는건 어떤가요?

2021-03-13 14:26 UTC, Kihyun92 commented on src/LoginForm.jsx
> +        />
이 부분도 `TextField`로 처리 가능할까요?

2021-03-13 14:26 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[0].payload).not.toBeNull();
아래 영상을 참고하시면 액션 객체를 검증하는 방식이 보일 겁니다.

액션 객체 배열 자체를 드러내서 표현하면 무슨 일이 벌어지는지 더 알기 쉬워집니다.

- https://youtu.be/L1dtkLeIz-M?t=2261

2021-03-14 14:10 UTC, Kihyun92 approved these changes
이번주도 정말 고생 많으셨습니다~ 👍🏼

과제 풀이 영상을 한번 보시면서 아샬님은 어떻게 구현하는지 확인해보셔도 좋을 것 같아요~ㅎㅎ

슬랙 채널에 회고 남겨주시면 머지하겠습니다! 😊

2021-03-22 12:15 UTC, merged