로그인폼과 레스토랑 리뷰폼 만들기
CodeSoom/react-week7-assignment-1 pull request #46
Opened 2021-03-10 12:06 UTC by yoonhe

코드리뷰 부탁드립니다!

## 진행상황
- 로그인폼 작업 완료
- 레스토랑 리뷰 폼 작업중

2021-03-10 12:09 UTC, yoonhe commented
로그인 요청 관련 질문이있습니다!

```js
const response = await fetch(url, {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
```

위와같이 post 요청을 하고있는데 

![image](https://user-images.githubusercontent.com/53102889/110627001-c86c4f00-81e4-11eb-8847-c74bbf67a607.png)
이런 에러가 발생합니다..

![image](https://user-images.githubusercontent.com/53102889/110627037-d4581100-81e4-11eb-82a0-80be7c44401d.png)
아이디디와 비밀번호는 이렇게 보내고있는데 

왜 로그인이 안되는것일까요..

2021-03-10 14:31 UTC, Kihyun92 requested changes
커밋을 보니 TDD cycle을 잘 지키려고 노력해주시는 것 같아요 👍🏼 

테스트 코드 또한 리팩터링의 대상입니다 ㅎㅎ

중복이 없고, 확장 가능한 코드를 작성하려고 노력해보시면 좋을 것 같네요~

2021-03-10 14:31 UTC, Kihyun92 commented on src/LoginContainer.jsx
> +  function handleSubmit(e) {
보통 e 라고 많이 적지만, 읽는 사람에 따라 여러 의미로 이해할 수 있을것 같아요.

좀 더 명확하게 event 라고 적어주는건 어떨까요?

2021-03-10 14:31 UTC, Kihyun92 commented on src/LoginContainer.test.jsx
> +  });
아래의 비밀 번호 입력 변경 테스트 코드와 매우 비슷한 로직인 것 같아요.

만약 다른 인풋이 추가된다면 또 하나의 비슷한 테스트가 추가될 것 같군요.

조금 더 개선할 방법이 없을까요? 🤔

2021-03-10 14:31 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +      password="1234"
테스트의 의도를 드러내주기위해 상수로 추출하는건 어떨까요? 😊

- https://refactoring.com/catalog/replaceMagicLiteral.html

2021-03-10 14:31 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
로그인 버튼을 클릭하면 onSubmit handler가 호출됩니다는 어떨까요?

2021-03-10 14:31 UTC, Kihyun92 commented on src/LoginForm.jsx
> +  function HandleChange(e) {
`HandleChange` -> `handleChange` 네이밍 형식을 맞춰주는게 좋겠네요~

2021-03-10 14:31 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[0]).toEqual(setAccessToken('ACCESS_TOKEN'));
아래 영상을 참고하시면 액션 객체를 검증하는 방식이 보일 겁니다.

액션 객체 배열 자체를 드러내서 표현하면 무슨 일이 벌어지는지 더 알기 쉬워집니다.

- https://youtu.be/L1dtkLeIz-M?t=2261

2021-03-11 01:41 UTC, yoonhe commented on src/LoginForm.jsx
> +  function HandleChange(e) {
앗 제가 왜 대문자로... 수정하겠습니다 ㅎㅎ!!

2021-03-11 06:52 UTC, yoonhe commented
```jsx
try {
    const accessToken = await postLogin({ email, password });

    dispatch(setAccessToken(accessToken));
  } catch (error) {
    console.log('error ? ', error); // 112 line
  }
```
![image](https://user-images.githubusercontent.com/53102889/110747269-77f6ff00-8281-11eb-9739-fee1d5026ea1.png)

위와같은 코드를 테스트를 해주기위해 아래와같이 코드를 작성해보았습니다.

```jsx
jest.mock('./services/api'); // api mocking

it('catch error', async () => {
  const response = {
    status: 400,
  };

  global.fetch = jest.fn().mockRejectedValue(response);

  try {
    await expect(store.dispatch(requestLogin()));
  } catch (e) {
    expect(e).toEqual(response);
  }

  const actions = store.getActions();

  expect(actions[0]).toEqual(setAccessToken('ACCESS_TOKEN'));
});
});
```

그런데 이미 `jest.mock('./services/api')` 를 위에서 사용하고 있어서 `global.fetch = jest.fn().mockRejectedValue(response);` 이부분이 실행되지 않는지.. 테스트가 안되더라구요...

에러가 났을경우를 테스트해주고 싶은데 어떠한 방법으로 접근해야할지 모르겠습니다..

## 참고한 글
https://stackoverflow.com/questions/57309678/how-i-can-test-in-jest-line-with-throw-e
https://redux.js.org/recipes/writing-tests
https://www.ximedes.com/2017-02-03/test-redux-action-creators-with-jest/

2021-03-11 08:20 UTC, yoonhe commented on src/LoginForm.test.jsx
> +      password="1234"
`LOGIN_FIELDS.email` 이렇게 빼주었는데 괜찮은가요??
EMAIL, PASSWORD를 각각 상수로 뺴주는게 좋은지가 고민됩니다..!

2021-03-11 09:51 UTC, yoonhe commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
`listens "Log In" button click event` 이렇게 표현하면 될까요???

2021-03-11 12:41 UTC, yoonhe commented on src/LoginForm.test.jsx
> +      password="1234"
기현님 과제 파일에 있던 기존 코드들을 보니  api 테스트 파일은 상수를 사용하고 reducer, action 등등에는 상수가 사용되지 않았더라구요 혹시 상수를 써야하는 상황이 있고 쓰지말아야할 상황이 무엇인가요??

reducer나 action 테스트는 상태의 변화를  테스트하니까 상수를 사용하지 않는게 좋을까요?

어느 상황에 상수를 사용하고 사용하지 말아야하는지가 궁금합니다! ㅎㅎ

2021-03-11 15:09 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
`calls onSubmit handler when click Log In button` 은 어떤가요? 🤔

2021-03-11 16:37 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +      password="1234"
아 조금 적절하지 않은 커맨트였을 수 있겠네요.

저는 아래와 같이 간단하게 함수 내에서 상수로 추출해서 사용하면 좋을 것 같아 커맨트를 남겼었어요 ㅎㅎ 
```javascript
const MOCK_EMAIL = "test@test.com";
const MOCK_PASSWORD = "1234";
```
작업하신대로 fixture로 따로 추출하신 것도 테스트와 같이 가짜 아이디, 비밀번호를 사용하는 곳에 적용하기 좋아보이네요 :)

질문에 답변을 드리면 reducer나 action이 상수를 사용할지 말지를 결정하진 않을 것 같아요. 좀 더 단순하게 해당 값만 보는 것 같아요 ㅎㅎ 

본인이 판단하기에 해당 값이 재사용 되거나 혹은 의도를 더 드러내고 싶을때 상수로 추출해주면 좋아요.

Magic literal 관련해서는 이전에 윤석님이 잘 설명해주신 커맨트가 있는데 한번 보시면 좋을 것 같아요~

- https://github.com/CodeSoom/react-week7-assignment-1/pull/26#discussion_r516718860

2021-03-11 16:43 UTC, Kihyun92 commented
postLogin API에서 에러가 내려왔을때 어떤 처리를 해줄건가요?

그러면 프론트에서 에러가 내려왔을때 테스트를 통해 어떤걸 확인해야할지 알 수 있을 것 같아요.

질문 관련해서는 저도 좀더 찾아보고 말씀드릴게요 :)

2021-03-11 16:45 UTC, Kihyun92 requested changes

2021-03-11 16:45 UTC, Kihyun92 commented on src/LoginContainer.jsx
> +        </div>
단순한 부분이지만 LoginForm 컴포넌트와 같이 컴포넌트로 추출해주는건 어떨까요?

2021-03-12 10:15 UTC, yoonhe commented on src/LoginForm.test.jsx
> +      password="1234"
오.. 좋은 예시글 감사합니다!

2021-03-12 10:39 UTC, yoonhe commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
무엇을 테스트 하려는지가 명확하게 보여서 더 좋은거같아요!

2021-03-12 10:39 UTC, yoonhe commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
그럼 onChange 이벤트도 동일핳게 변경해주는게 좋을까요?
변경전 :
`it('listens email input change event')`

변경후 : 
`it('calls onChange handler when input change')`

2021-03-12 10:39 UTC, yoonhe commented on src/LoginContainer.jsx
> +        </div>
LogfinForm 컴포넌트에 추가해주었습니다 ㅎㅎ

2021-03-12 12:19 UTC, yoonhe commented
진행방향을 잘못잡았습니다...

아래처럼 리뷰의 상태값을 관리해야하는데
```js
{
  restaurant : {
    reviews: []
  }
}
```

이렇게 작업해 버렸습니다 ㅎㅎㅎ
```
{
  restaurant : {},
  restaurantReviews: []
}
```

수정할 부분이 많아질것 같아서 ㅎㅎㅎㅎ 수정한 부분은 내일 PR에 담아 보낼게요... ㅜㅜ 내일도 코드리뷰 부탁드립니다 기현님 ..흑

테스트코드를 잘못 작성하고 있었던 것일까요... 잘못된 방향으로 가고있는데 다하고 나서야 발견해버렸습니다. ㅜㅜㅜ

2021-03-12 15:58 UTC, Kihyun92 commented on src/LoginForm.test.jsx
> +  it('listens click event', () => {
다른 부분도 조금 더 명확하게 수정할 부분이 있다면 해주면 좋겠네요 :)

말씀해주신 부분은 조금 당연한 느낌이 드는 것 같아요.

`it('calls onChange handler when change email')`은 어떤가요? 🤔

2021-03-12 16:00 UTC, Kihyun92 commented on src/LoginContainer.jsx
> +        </div>
Login과 구분되게 Logout 이라는 컴포넌트로 따로 추출하는건 어떨까요?

2021-03-12 16:16 UTC, Kihyun92 requested changes
코드량이 많아져서 저도 상태값을 제대로 체크 못했네요! 😅

리팩터링 잘 해주신 것 같아요 👍🏼

2021-03-12 16:16 UTC, Kihyun92 commented on src/App.test.jsx
> +    it('renders tje login page', () => {
오타가 있는 것 같아요~

2021-03-12 16:16 UTC, Kihyun92 commented on src/LoginContainer.jsx
> +    <>
이 fragment 태그는 제거해도 될 것 같네요~

2021-03-13 08:21 UTC, yoonhe commented
```js
try {
  const accessToken = await postLogin({ email, password });

  localStorage.setItem('accessToken', accessToken);

  dispatch(setAccessToken(accessToken));
} catch (error) {
  dispatch(requeryLoginError());
}
```
위의 코드에 대한 테스트코드를 아래와같이 구현해보았는데요

`postLogin` 함수를 mocking하여 `mockRejectedValue('error')` 를 사용해 해당 테스트 안에서만 `postLogin`이 실행되었을때 `reject`가 반환되게 하여 catch에서 에러가 잡히도록 해주었습니다. 제가 적절하게 사용하게 맞나요?.. 틀린게 있으면 꼭 말씀해주세요 ㅜㅜ

```js
beforeEach(() => {
  jest.clearAllMocks();
  postLogin.mockRejectedValue('error');
});

it('runs requeryLoginError', async () => {
  await store.dispatch(requestLogin());

  const actions = store.getActions();

  expect(actions).toEqual([{
    type: 'requeryLoginError',
  }]);
});
```

2021-03-13 09:01 UTC, yoonhe commented
> postLogin API에서 에러가 내려왔을때 어떤 처리를 해줄건가요?
그러면 프론트에서 에러가 내려왔을때 테스트를 통해 어떤걸 확인해야할지 알 수 있을 것 같아요.

기현님 postLogin API에서 에러가 내려왔을때 아래와같이 처리해주었는데요,
에러가 발생하면 당연히 catch문을 탈거라 예상하고 테스트를 해보았는데 catch문의 콘솔은 찍히지않고 
`setAccessToken(accessToken)`이 실행되어 accessToken에 undefined가 저장되더라구요... 

제가 무엇을 놓치고 있는것일까요...?.. ㅜ

```js
try {
      const accessToken = await postLogin({ email, password });

      localStorage.setItem('accessToken', accessToken);

      dispatch(setAccessToken(accessToken));
    } catch (error) {
      console.log('error 발생!');
      dispatch(requestLoginError());
    }
```

2021-03-13 10:45 UTC, yoonhe commented
e2e 테스트 관련하여 질문이 있습니다..

테스트 코드를 보고 제가 웹을 띄워서 테스트 순서대로 직접 실행해보면 다 잘 되는데 e2e 테스트에서 로그인 관련된 테스트들이 통과가 되지않네요...
![image](https://user-images.githubusercontent.com/53102889/111027599-8fc2b480-8434-11eb-8597-33ef65da461a.png)

왜 통과가 안되는걸까요?..

2021-03-13 13:31 UTC, Kihyun92 commented
> ```js
> try {
>   const accessToken = await postLogin({ email, password });
> 
>   localStorage.setItem('accessToken', accessToken);
> 
>   dispatch(setAccessToken(accessToken));
> } catch (error) {
>   dispatch(requeryLoginError());
> }
> ```
> 
> 위의 코드에 대한 테스트코드를 아래와같이 구현해보았는데요
> 
> `postLogin` 함수를 mocking하여 `mockRejectedValue('error')` 를 사용해 해당 테스트 안에서만 `postLogin`이 실행되었을때 `reject`가 실행되게하여 catch에서 에러가 잡히도록 해주었습니다. 제가 적절하게 사용한게 맞을까요?.. 틀린게 있으면 꼭 말씀해주세요 ㅜㅜ
> 
> ```js
> beforeEach(() => {
>   jest.clearAllMocks();
>   postLogin.mockRejectedValue('error');
> });
> 
> it('runs requestLoginError', async () => {
>   await store.dispatch(requestLogin());
> 
>   const actions = store.getActions();
> 
>   expect(actions).toEqual([{
>     type: 'requestLoginError',
>   }]);
> });
> ```

답변이 늦었네요 🙏 

적절하게 테스트 해주신 것 같아요! 👍🏼

2021-03-13 13:45 UTC, Kihyun92 commented
> > postLogin API에서 에러가 내려왔을때 어떤 처리를 해줄건가요?
> > 그러면 프론트에서 에러가 내려왔을때 테스트를 통해 어떤걸 확인해야할지 알 수 있을 것 같아요.
> 
> 기현님 postLogin API에서 에러가 내려왔을때 아래와같이 처리해주었는데요,
> `postLogin API`에서 에러가 발생하면 당연히 `postLogin` 함수를 실행하는 부분의 아래부분은 무시되고
> `catch` 안에 있는 코드가 실행될거라 예상하고 테스트를 해보았는데 `catch` 안의 콘솔은 찍히지않고
> `setAccessToken(accessToken)`이 실행되어 accessToken에 undefined가 저장되더라구요...
> 
> 제가 무엇을 놓치고 있는것일까요...?.. ㅜ
> 
> ```js
> try {
>       const accessToken = await postLogin({ email, password });
> 
>       localStorage.setItem('accessToken', accessToken);
> 
>       dispatch(setAccessToken(accessToken));
>     } catch (error) {
>       console.log('error 발생!');
>       dispatch(requestLoginError());
>     }
> ```
> 
> `postLogin` 함수 안에서 `throw new Error();` 이렇게 에러를 발생시켜주니 catch문 안에 코드가 실행되는데..
> 로그인이 실패했을때 서버에서 400 에러를 응답해주는데 에러로 잡히지 않는 이유가 무엇일까요? ㅜㅜ
> 
> ![image](https://user-images.githubusercontent.com/53102889/111025579-5be19200-8428-11eb-8568-b0f1aeb80c4f.png)
> 
> 위의 문제를 해결하기위해 아래와같이 코드를 구현해보았는데.. 이게 맞는 방법인지는 잘 모르겠습니다..! 보시고 리뷰 부탁드립니다 ㅎㅎ
> 
> ```js
> export async function postLogin({ email, password }) {
>   const url = 'https://eatgo-login-api.ahastudio.com/session';
>   const response = await fetch(url, {
>     method: 'POST',
>     headers: {
>       'Content-Type': 'application/json',
>     },
>     body: JSON.stringify({ email, password }),
>   });
>   const { accessToken } = await response.json();
> 
>   if (!accessToken) { // 추가한 부분
>     throw new Error();
>   }
> 
>   return accessToken;
> }
> ```

> `postLogin API`에서 에러가 발생하면 당연히 `postLogin` 함수를 실행하는 부분의 아래부분은 무시되고 `catch` 안에 있는 코드가 실행될거라 예상하고 테스트를 해보았는데

이 부분이 잘못 예상하신 부분입니다. 구현하신 postLogin API에서는 따로 에러인 경우 위와 같은 처리를 해주지 않았으니까요 ㅎㅎ 그렇기 때문에 해은님께서 에러를 throw 하도록 추가하신 것 같구요 :)

방식의 차이가 있을 수 있겠지만, 아래와 같이 처리 할수도 있겠네요~

```javascript
try {
  const accessToken = await postLogin({ email, password });
  if (accessToken) {
    localStorage.setItem('accessToken', accessToken);
 
    dispatch(setAccessToken(accessToken));
  }
}
```

비슷하게 API 응답값에 백엔드에서 미리 정의된 에러 코드(HTTP 상태 응답 코드와 별개의 코드)를 내려줘서 그걸 기반으로 에러 처리를 하기도 합니다.

2021-03-13 13:52 UTC, Kihyun92 commented
> e2e 테스트 관련하여 질문이 있습니다..
> 
> 테스트 코드를 보고 제가 웹을 띄워서 테스트 순서대로 직접 실행해보면 다 잘 되는데 e2e 테스트에서 로그인 관련된 테스트만 통과가 되지않네요...
> ![image](https://user-images.githubusercontent.com/53102889/111027599-8fc2b480-8434-11eb-8597-33ef65da461a.png)
> 
> 왜 통과가 안되는걸까요?..

같은 텍스트인가요? 테스트 코드를 보니 `I.see('Log out');`인데, 화면엔 `Log Out`이 그려지고 있는 것 같아요~ 

한번 확인해보시겠어요?

2021-03-13 14:27 UTC, yoonhe commented on src/LoginContainer.jsx
> +        </div>
앗 이부분을 반영을 못했네요 ㅜㅜㅜ 내일 꼭 반영할게요 ㅎㅎㅎ!!

2021-03-14 06:02 UTC, yoonhe commented
> 같은 텍스트인가요? 테스트 코드를 보니 I.see('Log out');인데, 화면엔 Log Out이 그려지고 있는 것 같아요~
한번 확인해보시겠어요?

ec2 테스트를 의심한 것을 반성합니다 ㅎㅎㅎㅎㅎㅎ
왜 제눈엔 대소문자가 다른것이 안보였을까요 ㅜㅜㅜ 반성합니다... 눈을 더 크게 뜨고다닐게요...

2021-03-14 06:18 UTC, yoonhe commented
> 비슷하게 API 응답값에 백엔드에서 미리 정의된 에러 코드(HTTP 상태 응답 코드와 별개의 코드)를 내려줘서 그걸 기반으로 에러 처리를 하기도 합니다.

기현님 아래와 같은 코드에서 fetch 요청을 보냈을때 요청이 실패하였을 경우,
```js
export async function postLogin({ email, password }) {
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ email, password }),
  });
  const { accessToken } = await response.json();

  return accessToken;
}
```

```js
try {
      const accessToken = await postLogin({ email, password });

      localStorage.setItem('accessToken', accessToken);

      dispatch(setAccessToken(accessToken));
    } catch (error) {
      console.log('error 발생!');
      dispatch(requestLoginError());
    }
```
postLogin 함수를 사용하는 쪽에서 api 요청중 에러가 발생함을 자동으로 감지하고 catch 문으로 이동되는 것이 아니라 
postLogin 함수에서 api 요청중 에러가 발생하여 응답값이 undefined일 경우 `throw new Error()` 같은 방법으로 에러를 발생시켜주는 코드를 작성해야만 아래의 catch 문에서 `requestLoginError`를 디스패치해주는 코드가 실핼될 수 있는건가요??

저는 api 요청 함수를 try 안에서 사용하는 경우 api 요청시 서버에서 에러가 발생했을때 catch 안에서 사용한 api 요청 함수의 아랫부분은 무시되고 catch문이 실행된다고 알고있었습니다..

제가 잘못 알고 있었던 부분이 있는거 같아 확인차 재질문드립니다..ㅎㅎ

2021-03-14 13:54 UTC, Kihyun92 commented
> e2e 테스트를 의심한 저를 반성합니다 ㅎㅎㅎㅎㅎㅎ
> 왜 제눈엔 대소문자가 다른것이 안보였을까요 ㅜㅜㅜ 반성합니다... 눈을 더 크게 뜨고 다닐게요...

그래도 간단하게 해결할 수 있어 다행입니다! 😊

2021-03-14 14:03 UTC, Kihyun92 commented
> 제가 잘못 알고 있었던 부분이 있는거 같아 이번에 확실하게 알고 넘어가고 샆이서 재질문드립니다..ㅎㅎ
> 
> 기현님 아래와 같은 코드에서 fetch 요청을 보냈을때 요청이 실패하였을 경우,
> 
> ```js
> export async function postLogin({ email, password }) {
>   const response = await fetch(url, {
>     method: 'POST',
>     headers: {
>       'Content-Type': 'application/json',
>     },
>     body: JSON.stringify({ email, password }),
>   });
>   const { accessToken } = await response.json();
> 
>   return accessToken;
> }
> ```
> 
> ```js
> try {
>       const accessToken = await postLogin({ email, password });
> 
>       localStorage.setItem('accessToken', accessToken);
> 
>       dispatch(setAccessToken(accessToken));
>     } catch (error) {
>       console.log('error 발생!');
>       dispatch(requestLoginError());
>     }
> ```
> 
> postLogin 함수를 사용하는 쪽에서 api 요청중 에러가 발생함을 자동으로 감지하고 catch 문으로 이동되는 것이 아니라
> postLogin 함수에서 api 요청중 에러가 발생하여 응답값이 undefined일 경우 `throw new Error()` 같은 방법으로 프론트에서 에러를 발생시켜주는 코드를 작성해야만 아래의 catch 문에서 `requestLoginError`를 디스패치해주는 코드가 실핼될 수 있는건가요??
> 
> 저는 `api 요청 함수`를 `try` 안에서 사용하는 경우 `api` 요청시 서버에서 에러가 발생했을때 `catch` 안에서 사용한 `api 요청 함수`의 아랫부분은 무시되고 `catch`문이 실행된다고 알고있었습니다.. ===> 이부분이 제가 잘못 알고 있었던 부분 맞죠?..!

제가 좀더 자세히 커맨트를 드리지 못했던 것 같네요 🙇🏻‍♂️

실제 response 를 봐보기 전엔 흔히 착각할 수 있는 부분입니다 :) 

실제 HTTP 에러 상태 값이 내려오더라도 fetch가 반환하는 Promise 객체에서는 reject 가 일어나지 않습니다. ok 상태값이 false 인 resolve 가 반환되죠. 물론 특정 상황에는 reject 값이 내려오지만, 자세한 내용은 아래 문서 확인해보시면 좋을 것 같아요!

- https://developer.mozilla.org/ko/docs/Web/API/Fetch_API/Using_Fetch
> fetch()로 부터 반환되는 Promise 객체는 HTTP error 상태를 reject하지 않습니다. HTTP Statue Code가 404나 500을 반환하더라도요. 대신 ok 상태가 false인 resolve가 반환되며, 네트워크 장애나 요청이 완료되지 못한 상태에는 reject가 반환됩니다.

2021-03-14 14:08 UTC, Kihyun92 approved these changes
이번주도 정말 고생 많으셨습니다~ 👍🏼

쉽지 않은 과제였는데 많이 고민하고 진행 해주셔서 리뷰 드릴게 많이 드린게 없는 것 같아요!

그리고 부족한 답변에 대해 다시 피드백 주셔서 감사합니다 :) 개인적으로 바쁜 주차여서 신경써서 리뷰드리지 못한 것 같아 아쉽네요. 반성합니다🙇🏻‍♂️

과제 풀이 영상을 한번 보시면서 아샬님은 어떻게 구현하는지 확인해보셔도 좋을 것 같아요~ㅎㅎ

슬랙 채널에 회고 남겨주시면 머지하겠습니다! 남은 시간도 화이팅입니다 💪

2021-03-15 06:49 UTC, yoonhe commented
늦어서 죄송합니다

회고글 작성하였습니다 ㅎㅎㅎ
https://velog.io/@heyoon/%EB%A6%AC%EC%95%A1%ED%8A%B8-7%EC%A3%BC%EC%B0%A8-%ED%9A%8C%EA%B3%A0

2021-03-22 12:16 UTC, merged