Feature/login
CodeSoom/react-week7-assignment-1 pull request #49
Opened 2021-06-14 14:09 UTC by dngwoodo

이번주는 강의가 많이 기네요! 이번주도 잘 부탁드리겠습니다 🔥

2021-06-14 14:23 UTC, Kihyun92 commented
빠른 PR 좋아요 👍🏼 👍🏼

2021-06-15 13:38 UTC, Kihyun92 requested changes
TDD cycle을 잘 지키며 진행하고 계신 것 같아요 👍🏼 

리팩터링도 잘해주고 계시네요 좋습니다 :)

2021-06-15 13:38 UTC, Kihyun92 commented on src/LoginFormContainer.jsx
> +      fields={{ email, password }}
구조분해할당해서 가져온 값들을 다시 객체로 넘겨줄 필요는 없을 것 같아요~

구조분해할당을 하지 않고 넘겨줘서 자식컴포넌트에서 처리하거나 email, password를 각각 props로 넘기는건 어떨까요?

2021-06-17 13:14 UTC, dngwoodo commented
남은 부분 
- [ ] accessToken을 localStorage에 저장
- [ ] sendReview 테스트 작성
- [ ] 로그인 되었을 때와 로그인 되지 않았을 때 context로 나눠서 테스트

2021-06-17 14:07 UTC, Kihyun92 requested changes
너무 잘 해주고 계셔서 리뷰 드릴 부분을 찾기 쉽지 않네요 😄

진행하시면서 의논할 부분이 생기면 바로 말씀해주세요~!

2021-06-17 14:12 UTC, Kihyun92 commented
>  sendReview에서 dispatch(loadRestaurant({ restaurantId })); 가 들어가있는데 테스트를 어떻게 할 수 있을지

`mockStore`를 사용해서 확인할 순 없을까요? 🤔

2021-06-18 12:05 UTC, dngwoodo commented
밖이라 커멘트를 폰으로 남깁니다. 궁금한점들을 주석으로 질문: 으로 남겨두었습니다. 피드백 주시면 감사하겠습니다.

줄바꿈 관련되서 피드백주신건 오늘 주실 피드백과 같이 수정해서 올리겠습니다! 항상 꼼꼼히 리뷰해주셔서 감사합니다 :)

2021-06-18 14:21 UTC, dngwoodo commented on src/RestaurantReviews.jsx
> +        name, score, description,
아 이 부분은 id는 li의 props로 사용되고 다른 아이들은 children으로 사용되서 나눠졌습니다. 나누는 기준을 세운다는게 참 힘든 것 같습니다 😂

2021-06-18 14:22 UTC, dngwoodo commented on src/RestaurantContainer.jsx
> +      <ReviewForm
피드백 감사합니다. 처리했습니다!

2021-06-18 14:23 UTC, dngwoodo commented on src/ReviewForm.jsx
> +  onSubmit,
이 부분은 input의 props로 
* score, onChange와 연관
* description, onChange와 연관
이 있으므로 같은줄에 나눴고

onSubmit은 버튼의 props로 사용되기 때문에

이렇게 나눠줬습니다!

2021-06-18 14:35 UTC, Kihyun92 requested changes

2021-06-18 14:35 UTC, Kihyun92 commented on src/RestaurantPage.test.jsx
> +  // 좀 더 적절하지 않나 질문드립니다.
말씀하신 방법도 괜찮네요. 😄

다만 '/restaurants/1'를 패스를 가질때 라우팅 처리에 의해 RestaurantPage가 처리되는 것이기 때문에 MemoryRouter 로 감싸서 처리해주는 방식이 사용 설명 측면에서 저는 더 명확해보이는 것 같아요.

2021-06-18 14:35 UTC, Kihyun92 commented on src/RestaurantPage.test.jsx
> +    // 질문: 의미상 beforeEach에 given을 넣는 것이 맞는 것 같은데 트레이너님 생각은 어떠신가요?
괜찮은 것 같습니다 :)

2021-06-18 14:35 UTC, Kihyun92 commented on src/actions.test.js
> +  // 질문: thunk함수안에 thunk함수가 있다보니 어떻게 테스트를 해줘야 될지 잘모르겠습니다.
아래 영상을 참고하셔서 액션 객체를 검증하는 방법을 확인해보셔도 좋을 것 같네요 :)

액션 객체 배열 자체를 드러내서 표현하면 무슨 일이 벌어지는지 더 알기 쉬워집니다.

- https://youtu.be/L1dtkLeIz-M?t=2261

2021-06-18 14:35 UTC, Kihyun92 commented on src/actions.test.js
> +// 만약 하지 않아도 jestdom의 global.localStorage때문에 에러는 나지 않는 것 같습니다.
넵 해주지 않아도 될 것 같아요.

2021-06-18 14:40 UTC, Kihyun92 commented on src/ReviewForm.jsx
> +  onSubmit,
기준이 있는 건 좋은 것 같아요~ 👍🏼 

개인적으로는 이것도 객체니까 이런 줄바꿈이 조금 어색해 보이는것 같네요 ㅎㅎ 팀 내 컨벤션이라면 상관없지만, props 를 destructuring 해줄때 서로 연관있는것 끼리 같은 줄에 두는 것보다 네이밍으로 의도와 연관성을 드러내주는 것도 좋을 것 같아요.

2021-06-18 17:33 UTC, dngwoodo commented
질문:
1. 알려주신 import/order를 적용시켜보았는데요. 트레이너님의 import/oreder 옵션의 셋팅이 궁금합니다.

2. https://github.com/CodeSoom/react-week7-assignment-1/pull/49/commits/63ef4b25a53efae7bddd5ce7d1d86983a19f800e 에서 sortedReviews를 잘 테스트 했나요?

3. sendReview의 테스트에 관해서..

2021-06-18 17:38 UTC, dngwoodo commented on src/actions.test.js
> +      expect(actions[1]).toEqual(setReviews(undefined));
원래대로라면 setReviews가 actions[0]에 존재해야합니다.  내부적으로 async/await가 있긴하지만 현재 테스트에서는 먹히지 않아서 뒤에 들어가게 된 것 같습니다. 이 부분은 어떻게 처리하는 것이 좋을까요?

2021-06-18 17:42 UTC, dngwoodo commented on src/LoginFormContainer.jsx
> +      )}
피드백 감사합니다. https://github.com/CodeSoom/react-week7-assignment-1/pull/49/commits/029ab249e848abcf54c161e64b33de84cfe5cee8 에서 수정했습니다!

2021-06-18 17:49 UTC, dngwoodo commented on src/RestaurantContainer.test.jsx
> +    // 질문1: logged out일 때는 ui 테스팅이 되버려서 따로 넣지는 않았습니다. 트레이너님은 이런 상황에 어떻게 하시나요?
로그아웃 했을 때를 말씀하신걸까요?

로그아웃 했을 때 노출되는 ui가 없는 지는 Page 컴포넌트에서 테스트하고 있기 때문에 굳이 해주진 않았는데 고민이 조금 되네요

2021-06-18 17:49 UTC, dngwoodo commented on src/RestaurantContainer.test.jsx
> +    // 질문2: useEffect안의 loadRestaurant때문에 toBeCalledWith는 사용하지 못하는 상황입니다. toBeCalledTimes만으로 적당할까요?
이 부분은 조금 아쉬운 것 같긴합니다. 하지만 방법이 없으니 이렇게 테스트를 진행해봐야겠네요 ㅠ

2021-06-18 17:54 UTC, dngwoodo commented on src/RestaurantPage.test.jsx
> +  // 좀 더 적절하지 않나 질문드립니다.
이 부분은 Route컴포넌트를 사용하지 않는 컴포넌트이기 때문에 `<MemoryRouter initialEntries={['/restaurants/1']}>`를 쓰게 되었을 때 `console.log(id)`를 하게 되면 undefined가 뜨게 되기 때문에 저렇게 테스트를 하는게 적절하지 않나 생각을 했었습니다.

현재 테스트에서는 별 상관은 없지만 제대로 동작하지 않는 코드를 사용 설명측에서 좀 더 명확해 보인다면 사용하는게 올바른 방법일까요 ?

2021-06-18 17:56 UTC, dngwoodo commented on src/actions.test.js
> +  // 질문: thunk함수안에 thunk함수가 있다보니 어떻게 테스트를 해줘야 될지 잘모르겠습니다.
답변 감사합니다. 해당 영상에서는 thunk함수안에 기본적인 action들만 테스트하는 것 같습니다. thunk안에 thunk가 들어가있는 부분이 조금 헷갈립니다. https://github.com/CodeSoom/react-week7-assignment-1/pull/49#discussion_r654589906 여기에 재질문 올려놨습니다! 한번 봐주시면 감사하겠습니다 :)

2021-06-18 17:57 UTC, dngwoodo commented on src/actions.test.js
> +// 만약 하지 않아도 jestdom의 global.localStorage때문에 에러는 나지 않는 것 같습니다.
감사합니다 :) storage.test.js부분을 커버리지를 위해 작성을 해봤는데 잘했는지 의문이네요 😅

2021-06-19 14:46 UTC, Kihyun92 commented on src/RestaurantContainer.test.jsx
> +    // 질문1: logged out일 때는 ui 테스팅이 되버려서 따로 넣지는 않았습니다. 트레이너님은 이런 상황에 어떻게 하시나요?
테스트는 본인이 안심할 수 있느냐에 따라 해주시면 될 것 같아요~

Page 컴포넌트에서 테스트 했다면 처리해주지 않아도 될 것 같습니다 :)

2021-06-19 15:46 UTC, Kihyun92 requested changes
> 질문:
> 
> 1. 알려주신 import/order를 적용시켜보았는데요. 트레이너님의 import/oreder 옵션의 셋팅이 궁금합니다.

아래와 같습니다~
```
    'import/order': ['error', {
      'groups': [
        'builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object'
      ],
      'pathGroups': [
        {
          pattern: './style',
          group: 'object',
          position: 'after'
        }
      ],
      'newlines-between': 'always'
    }],
```

> 2. [63ef4b2](https://github.com/CodeSoom/react-week7-assignment-1/commit/63ef4b25a53efae7bddd5ce7d1d86983a19f800e) 에서 sortedReviews를 잘 테스트 했나요?

잘 해보신 것 같아요~ 👍🏼  굳이 리뷰를 하자면 forEach 문 안에서 이렇게 처리할 수 있을 것 같군요.
```
 sortedReviews.forEach((sortReview, index) => {
      expect(getAllByTestId('review-name')[index]).toHaveTextContent(sortReview.name);
      expect(getAllByTestId('review-score')[index]).toHaveTextContent(sortReview.score);
      expect(getAllByTestId('review-description')[index]).toHaveTextContent(sortReview.description);
    });
```

2021-06-19 15:46 UTC, Kihyun92 commented on src/RestaurantPage.test.jsx
> +  // 좀 더 적절하지 않나 질문드립니다.
아 이 부분은 제가 잘못 리뷰 한 것 같네요.😅  말씀하신대로 params가 없는 경우에는 useParams를 사용해서 id 값을 가져오기 때문에 mocking 하여 테스트하는게 좋을 것 같습니다~ 🙏🏻

2021-06-19 15:46 UTC, Kihyun92 commented on src/services/storage.test.js
> +describe('storage', () => {
storage 테스트는 간단히 잘 동작하는지만 테스트하면 좋을 것 같아요.

```
test('storage', () => {
  saveItem('accessToken', 'ACCESS_TOKEN');

  expect(loadItem('accessToken')).toBe('ACCESS_TOKEN');

  removeItem('accessToken');

  expect(loadItem('accessToken')).toBeNull();
});

```

`localStorage`의 wrapper라서 어떤 일을 하는지 명세하는 역할로만 간단하게 테스트를 작성해도 좋을 것 같습니다~

2021-06-19 16:02 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[1]).toEqual(setReviews(undefined));
이 부분은 좀 더 확인해봐야할 것 같지만, 비동기 처리라서 순서가 보장되지 않을 수 있겠다는 생각이드네요. 🤔

sendReview action에서 각 action 들의 순서가 중요하지 않다면 dispatch가 됐는지만 확인해줘도 좋을 것 같네요.

2021-06-20 12:10 UTC, dngwoodo commented on src/actions.test.js
> +      expect(actions[1]).toEqual(setReviews(undefined));
감사합니다. 이 부분은 순서를 보장할 수 있게 할 수 있는 방법이 따로 없나보군요. 트레이너님은 실무에서 이런 상황일 때 제가 처리한 것처럼 그냥 dispatch가 됐는지만 체크하시나요?

2021-06-20 12:14 UTC, dngwoodo commented on src/services/storage.test.js
> +describe('storage', () => {
아하! 감사합니다. 그럼 이 부분은 jsdom이 localStorage를 내부적으로 구현해놨으니 그냥 저렇게만 테스트해보면 된다는 것일까요?

2021-06-20 15:44 UTC, Kihyun92 commented on src/services/storage.test.js
> +describe('storage', () => {
넵. 저희가 localStorage 기능 자체를 테스트할 필요는 없을 것 같고, 잘 동작하는지만 테스트 해줘도 좋을 것 같아서 커맨트 남겼습니다.

더 테스트를 해보고 싶다면 해보셔도 좋을 것 같습니다~ 😄

2021-06-20 15:53 UTC, Kihyun92 commented on src/actions.test.js
> +      expect(actions[1]).toEqual(setReviews(undefined));
넵, 개인적으로는 비동기에서 dispatch 됐는지 확인하는 것 외에 순서가 보장되어야 하는 경우에 대해서 테스트를 해본 적은 없던 것 같아요.🤔 비동기처리에서 순서가 보장되려면 로직 자체가 달라질 거고 그에 따라 테스트도 달라질 것 같습니다.

혹시나 방법이 있을 수 있으니 저도 조금 더 찾아보고 공유드릴게요~!

2021-06-20 16:00 UTC, Kihyun92 approved these changes
이번 주도 고생하셨습니다~

과제 풀이 영상을 보시고 아샬님은 어떻게 접근하시는지 보시면 좋을 것 같네요 :)

올려주신 회고도 확인했습니다. 정말 열심히 보내신 한주 였을 것 같아요! 
저도 덕분에 많은 자극이 됐습니다. 다음주도 화이팅입니다 ㅎㅎ

2021-08-08 07:51 UTC, merged