[7주차] 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/react-week7-assignment-1 pull request #50
Opened 2021-06-14 15:09 UTC by Hamill210

- 저와의 약속으로 PR 먼저 보내놓겠습니다
- 구현 예정 (수)

2021-06-15 13:39 UTC, Kihyun92 commented
기다리고 있겠습니다! 😄

2021-06-17 14:47 UTC, Kihyun92 requested changes
잘 진행하고 계신 것 같아요~ 👍🏼 

진행하시면서 어려운 점이나 의논할 부분이 있다면 말씀해주세요 :)

2021-06-17 14:47 UTC, Kihyun92 commented on src/LoginPage.test.jsx
> +    );
render 하는 로직이 중복되는 것 같은데 함수로 추출해서 사용해도 좋을 것 같네요~

2021-06-18 12:05 UTC, Hamill210 commented on src/LoginPage.test.jsx
> +    );
넵 함수로 추출해서 리팩토링하겠습니다. 피드백 감사합니다~

2021-06-19 14:00 UTC, Kihyun92 requested changes

2021-06-19 14:00 UTC, Kihyun92 commented on src/reducer.test.js
> +      expect(state.loginFields.password).toBe('password');
실제로 코드를 테스트하는 곳은 it함수 안에 있어야 합니다.

2021-06-19 14:04 UTC, Kihyun92 commented
리뷰 작성 페이지 구현도 기다리겠습니다~

2021-06-20 15:54 UTC, Kihyun92 commented
과제 풀이 영상을 꼭 보시면 좋을 것 같아요!

슬랙 채널에 회고 올려주시면 머지하겠습니다~

2021-08-08 07:51 UTC, merged