fix(....) 작업내용...
CodeSoom/react-week7-assignment-1 pull request #88
Opened 2022-07-18 11:50 UTC by Jongveloper

죄송합니다... fork를 받지 않고.. git을 클론하고 작업하는 바람에..
fork를 받고..다시 하느라 git 컨벤션을 지키지 못했습니다... 죄송합니다..

2022-07-18 14:14 UTC, daadaadaah requested changes
월요일부터 PR 아주 멋있습니당👍
코딩할 때, 마음을 좀더 차분이 가지고 과제를 수행해보시구~ 중간중간 빠진 속성들 다시한번 체크해봅시당!ㅎㅎfixture로 뺄 수 있는 것들도 있는지도 한번 체크해보세요~ㅎㅎ

그리고, 이렇게 미치못하게 한꺼번에 올려할 경우, 어디까지 작업하시고, 앞으로 어떤 기능 구현할 것인지 코멘트로 남겨주시면 좋을 것 같아요! 왜냐하면, 리뷰어 입장에서 이분이 이 기능을 모르고 기능 구현을 안하셨는지, 아니면 나중에 할 것인지 파악하기가 어렵거든용!ㅎㅎ다음 PR 기대하고 있을게요~🔥

2022-07-18 14:14 UTC, daadaadaah commented on src/components/LoginForm.test.jsx
> +      origin: email,
`origin` 속성은 언제 필요한 것인가요?ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/components/TextField.jsx
> +        />
value 속성이 빠진 것 같아요! 넣어줍시당ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/components/TextField.jsx
> +      <div>
`div` 여러개 보다 Fragment(`<></>`) 로 묶어줘도 되지 않을까용?ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/components/TextField.test.jsx
> +        type={type}
여기도 value 속성이 빠진 것 같아요! 넣어줍시당ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/components/ReviewForm.jsx
> +      />
value 속성이 빠졌어요!

2022-07-18 14:14 UTC, daadaadaah commented on src/components/ReviewForm.jsx
> +export default function ReviewForm({ onChange, onSubmit }) {
input의 value 값도 필요할 것 같은데, 어떻게 생각하시나요?

2022-07-18 14:14 UTC, daadaadaah commented on src/container/LoginFormContainer.jsx
> +      <p>{accessToken}</p>
오잉? 토큰이 보이네용ㅎㅎ삭제해줍시당!🚀
토큰 유무에 따라 View 달라지는건 다음 PR에서 작업하실 예정이신가요?ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/container/LoginFormContainer.test.jsx
> +    </MemoryRouter>,
여기서, `MemoryRouter`는 왜 필요하신거예요?ㅎㅎ

2022-07-18 14:14 UTC, daadaadaah commented on src/container/RestaurantContainer.test.jsx
> +      },
테스트 코드에서는 `reviewFIelds` 상태가 있는데, `RestaurantContainer.jsx`에서는 빠진 것 같아요!

2022-07-18 14:14 UTC, daadaadaah commented on src/container/RestaurantContainer.test.jsx
> +  });
이 테스트는 어떤 상황을 테스트 하고 싶으셨나요? ㅎㅎ

2022-07-19 01:18 UTC, Jongveloper commented on src/components/LoginForm.test.jsx
> +      origin: email,
입력받는 email , password 속성에 필요합니다!
표현이 명확하지 않은 것 같네요!
ㅎㅎ 피드백 감사합니다
리팩토링 진행하겠습니다!

2022-07-19 01:19 UTC, Jongveloper commented on src/components/TextField.jsx
> +        />
엇..! ㅎㅎ 실수가 있었네요! 피드백 감사합니다!

2022-07-19 01:19 UTC, Jongveloper commented on src/components/TextField.jsx
> +      <div>
아하...ㅎㅎㅎ Fragment를 사용하다가 코드를 계속 수정하면서 ㅎㅎㅎ
div를 사용한 것 같습니다! 피드백 감사합니다!

2022-07-19 01:19 UTC, Jongveloper commented on src/components/TextField.test.jsx
> +        type={type}
헉..ㅠㅠㅠ TextField를 계속 실수했네요 ㅎㅎㅎ 피드백 감사합니다!

2022-07-19 01:20 UTC, Jongveloper commented on src/container/LoginFormContainer.jsx
> +      <p>{accessToken}</p>
앗 토큰 유무에 따라 View 가 달라지는 것을 구현했는데
토큰 보이는 것을 삭제를 못했네요! ㅎㅎ 피드백 감사합니다!

2022-07-19 01:22 UTC, Jongveloper commented on src/container/LoginFormContainer.test.jsx
> +    </MemoryRouter>,
앗 지금 보니 MemoryRouter가 현재는 필요없는 것으로 보입니다!
피드백 감사합니다1

2022-07-19 01:23 UTC, Jongveloper commented on src/container/RestaurantContainer.test.jsx
> +      },
앗 놓치는 부분이 있었네요! 피드백 감사합니다 ㅎㅎ

2022-07-19 01:24 UTC, Jongveloper commented on src/container/RestaurantContainer.test.jsx
> +  });
엇 이 부분은 한번 확인해보겠습니다!
피드백 감사합니다!

2022-07-19 11:45 UTC, Jongveloper commented
안녕하세요 트레이너님!
로그인과 로그아웃 상태의 뷰를 구현하고
localStorage로 token을 저장하는 것을 구현하였습니다!
리뷰 요청드립니다!
항상 감사합니다!

2022-07-20 03:12 UTC, daadaadaah requested changes

2022-07-20 03:12 UTC, daadaadaah commented on src/components/LoginForm.test.jsx
> +      expect(input.value).toBe(userInfo);
change 이벤트가 발생하기 이전의 상태값을 저장하고 싶었던 거군용!!ㅎㅎㅎ

2022-07-20 03:12 UTC, daadaadaah commented on src/container/RestaurantContainer.jsx
> +  const { score, description } = useSelector(get('reviewFields'));
`reviewFields`로 해서 통으로 ReviewForm에 넘겨줘도 될 것 같은데, 여기서 디스트럭처 하는 거랑 ReviewForm에서 디스트러처 하는 거랑 어떤 차이가 있을까요?ㅎㅎ한번 고민해보시고, 답변 달아주세용!😃

2022-07-20 03:12 UTC, daadaadaah commented on src/components/ReviewForm.jsx
> +        targetValue={score}
여기서, `target`의 의미가 어떤 의미를 갖나요? 그냥 `value`라고 했을 때랑 차이가 있나요?

2022-07-20 03:12 UTC, daadaadaah commented on src/container/LoginFormContainer.jsx
> +      fields={{ email, password }}
중복 코멘트

2022-07-20 03:12 UTC, daadaadaah commented on src/actions/actions.js
> +    saveItem('accessToken', accessToken);
commit은 logout 과 관련되어 있는데, 이와 관련 없는 작업 내역이 들어가 있네용! 다음에는 분리해서 commit해 봅시당!
그리고, 로그아웃했을 때, Token은 어떻게 해야 할지도 한번 고민해보세요!

2022-07-20 03:12 UTC, daadaadaah commented on src/container/LoginFormContainer.test.jsx
> +  context('when logged out', () => {
with/without accessToken 으로 구별해도 될 것 같아요! 그냥 이렇게 표현하는 것도 있다는 정도만 알아두셔도 됩니당!ㅎㅎ

2022-07-20 03:12 UTC, daadaadaah commented on src/components/LogoutForm.test.jsx
> +    const { container } = render(<LogoutForm />);
` <LogoutForm onClick={handleClick} />` 되도록 속성들은 계속 써주는게 좋아요!
추가로, 중복이 보이네요? 어떻게 하는게 좋을까요?

2022-07-20 09:46 UTC, Jongveloper commented on src/components/LoginForm.test.jsx
> +      expect(input.value).toBe(userInfo);
넵! 맞습니다 ㅎㅎ

2022-07-20 09:48 UTC, Jongveloper commented on src/container/RestaurantContainer.jsx
> +  const { score, description } = useSelector(get('reviewFields'));
앗 useSelector에서 디스트럭쳐를 바로 하면
성능에 미미하지만 좋지 않다고 알고있습니다!
이 부분 리팩토링하겠습니다!
피드백 감사합니다!

2022-07-20 09:58 UTC, Jongveloper commented on src/components/ReviewForm.jsx
> +        targetValue={score}
TextField에서 value를 사용하고 있어 중복됩니다...ㅠ
event.target.value 부분이어서
targetValue로 네이밍하였습니다!

2022-07-20 10:00 UTC, Jongveloper commented on src/actions/actions.js
> +    saveItem('accessToken', accessToken);
앗 넵 감사합니다!

2022-07-20 10:02 UTC, Jongveloper commented on src/container/LoginFormContainer.test.jsx
> +  context('when logged out', () => {
앗 토큰으로 테스트 문구를 변경하는게 좋은 것 같습니다!
항상 좋은 피드백 감사합니다!

2022-07-20 10:07 UTC, Jongveloper commented on src/components/LogoutForm.test.jsx
> +    const { container } = render(<LogoutForm />);
mockClear를 해주고
render함수를 만들어야할 것 같습니다!
피드백 감사합니다!

2022-07-20 11:16 UTC, Jongveloper commented
안녕하세요 트레이너님!
오늘 개인적인 사정이 있어
피드백 주신 부분에 대해 리팩토링 밖에 진행을 못했습니다...ㅠㅠ
내일 나머지 부분 처리하겠습니다
항상 감사합니다!

2022-07-21 00:02 UTC, daadaadaah commented on src/container/RestaurantContainer.jsx
> +  const { score, description } = useSelector(get('reviewFields'));
저는 성능 관점이 아니라 유지보수 관점에서 드린 피드백이었어요!ㅎㅎ
`reviewFields`의 속성이 계속 추가되거나 네이밍이 바뀌어서 수정해야 할 경우, 수정해야 할 파일의 갯수를 생각해보면 어느게 좀더 유지보수에서 나은지 아실 수 있을 거예요

2022-07-21 00:15 UTC, daadaadaah reviewed
바쁘신 와중에 매일 PR 날려주시는 모습 너무 좋네요👍 과제 계속 진행해주세요! 🚀

2022-07-21 00:15 UTC, daadaadaah commented on src/components/ReviewForm.jsx
> +        targetValue={score}
`TestField` 의 아래 코드에서 중복되군요! 
```jsx
// TextField.js 
  function handleChange(e) {
    const { target: { value } } = e;

    onChange({ name, value });
  }
```
저라면, `targetValue` 를 `value` 로 수정하고, `handleChange` 내부 코드를 변경할 것 같은데, 이런 방법도 있다는 것만 알아두셔도 괜찮을 것 같아요! 이렇게 하는 이유는 TextField를 사용하는 입장에서 좀더 명확하고 단순한 표현을 쓰게, 사용할 때 더 좋더라구요!ㅎㅎ

2022-07-21 13:59 UTC, Jongveloper commented
안녕하세요 트레이너님!
리뷰요청드립니다!
우선 지금까지 진행한 부분 테스트 코드 빈 부분을 채우는 작업을 진행했습니다!
ㅠㅠ...이것저것 처음 해보는 부분이 많아 코드를 수정하고 이러는 부분에 있어서
시간이 오래걸려 ㅠㅠㅠ 리뷰목록이 보이는 부분은 내일 추가적으로 진행하겠습니다!
항상 감사합니다!

2022-07-22 01:29 UTC, daadaadaah requested changes
1. commit을 좀더 작은 단위로 관리하시는게 좋을 것 같아요!
2. fixture 하나 만들어서 테스트 데이터들 관리해봅시당!ㅎㅎ

2022-07-22 01:29 UTC, daadaadaah commented on src/actions/actions.js
> +    dispatch(loadRestaurant({ restaurantId }));
리뷰 작성 후에 restaurant는 왜 불러오시는 거예요?ㅎㅎ

2022-07-22 01:29 UTC, daadaadaah commented on src/actions/actions.test.js
> +      expect(localStorage.setItem).toHaveBeenCalled();
이 테스트에서 중요한건 ocalStorage 가 불린게 아니라 어떤 액션이 불려졌는지가 중요하지 않을까용?ㅎㅎ 테스트 시나리오에는 잘 적어두셨는데, 그게 실제 테스트 코드에는 반영이 되지 않은 것 같아요!

2022-07-22 01:29 UTC, daadaadaah commented on src/services/api.test.js
> +      expect(accessToken).toEqual(accessToken);
이 테스트가 실패할 일이 있을까요? 테스트 작성의 의미가 없도록 테스트 코드를 작성하신 것 같아요!
기대하는 결과 값을 어떻게 해야 할까요?

2022-07-22 01:29 UTC, daadaadaah commented on src/services/api.test.js
> +      expect(result).toEqual(result);
이 테스트가 실패할 일이 있을까요? 테스트 작성의 의미가 없도록 테스트 코드를 작성하신 것 같아요!
기대하는 결과 값을 어떻게 해야 할까요?

2022-07-22 01:29 UTC, daadaadaah commented on src/services/api.js
> +  return { result: 'success' };
return 값을 추가해주신 이유가 무엇인가용?ㅎㅎ
그리고, 만약에 fetch 가 실패할 경우에도 "success" 라고 던져주는게 적절할지에 대해 한번 생각해보세요!

2022-07-22 01:29 UTC, daadaadaah commented on src/services/storage.test.js
> +    });
1. 실제 테스트 코드에 맞게 좀더 적절한 테스트 시나리오를 작성해보세요!
현재 지금 어떤 것을 테스트 하고 있나요? 어떤 함수가 호출되는 것을 테스트 하고 있지 않나요??

2. [saveItem, loadItem가 만들어놓으신 형태](https://github.com/CodeSoom/react-week7-assignment-1/pull/88/files#diff-16a55a439703d0967faa67e0791bcf23b7447db46f56975c88b6a0ca0377f4f6)와 다릅니다! 맞게 수정해주세요~
아래 테스트도 마찬가지로 반영해주세요!

2022-07-22 10:43 UTC, Jongveloper commented on src/actions/actions.js
> +    dispatch(loadRestaurant({ restaurantId }));
리뷰 작성 후 작성한 리뷰를 받아오기 위해 불러왔습니다!ㅎㅎ

2022-07-22 10:43 UTC, Jongveloper commented on src/actions/actions.test.js
> +      expect(localStorage.setItem).toHaveBeenCalled();
앗 수정하겠습니다 피드백 감사합니다!

2022-07-22 10:44 UTC, Jongveloper commented on src/services/api.test.js
> +      expect(accessToken).toEqual(accessToken);
앗 이부분...수정하겠습니다!
피드백 감사합니다!

2022-07-22 10:44 UTC, Jongveloper commented on src/services/api.js
> +  return { result: 'success' };
이 부분 수정하겠습니다! 피드백 감사합니다!

2022-07-22 10:44 UTC, Jongveloper commented on src/services/storage.test.js
> +    });
헛...넵! 감사합니다!

2022-07-22 16:04 UTC, Jongveloper commented on src/services/storage.test.js
> +    });
이 부분 리팩토링을 어떻게 해야할지 감이 잘 잡히지 않는 것 같습니다..ㅠㅠ

2022-07-23 02:50 UTC, daadaadaah reviewed
종혁님, DM으로 말씀드린대로 승우님 PR 한번 참고하셔서 진행 상황 한번 정리해보세요!

이번주에 어떤 기능들을 구현해야 하는데, 지금 어떤 것까지 구현했는지 한번 리스트업해보시면, 생각을 정리하는데 도움되실거예요! 그리구 DM 한번 확인해주세요😃

2022-07-23 02:50 UTC, daadaadaah commented on src/actions/actions.test.js
> +      const accessToken = await postLogin({ email: 'dd@dd', password: '1234' });
api mock을 잘못 만들어주셔서 계속 꼬였던 것 같아요!ㅎㅎDM 확인해주세요~ㅎㅎ

2022-07-23 14:11 UTC, Jongveloper commented
안녕하세요 트레이너님!
깃 실수를 하는바람에... 실수한 부분들에 대한 내역을 코멘트로 남겨놓았습니다!
항상 감사합니다!

2022-07-23 15:29 UTC, daadaadaah commented
> 안녕하세요 트레이너님! 깃 실수를 하는바람에... 실수한 부분들에 대한 내역을 코멘트로 남겨놓았습니다! 우선은 과제 완료를 목표로 과제를 진행하였는데 코멘트와 제 코드를 보니 우선 제가 봐도 리팩토링 할 곳이 보여서... 리팩토링은 내일 또 진행하겠습니다! 너무 늦게 과제를 제출하여 죄송합니다...! 만약 피드백을 주실 수 있다면...! 피드백 주시면 감사하겠습니다! 항상 감사합니다!

깃 실수가 어느 commit에 담건가요? 어느 부분이 문제인지 알려주시면, 도움을 드릴 수 있을 것 같아서요!ㅎㅎ

2022-07-23 15:34 UTC, Jongveloper commented
refactor(sendReview) 테스트 문구 수정
이라는 커밋 메시지 파일에 여러가지를 실수로
같이 올려 ㅜㅜ push하는 바람에
코멘트를 하나씩 남겨놓았습니다!

2022-07-24 03:58 UTC, daadaadaah commented on src/services/storage.test.js
> +    });
saveItem의 매개변수는 key, value 인데, 13번줄 보시면, 지금 하나만 받고 있어요!
loadItem 도 한번 매개변수로 어떻게 받는지 확인해보세요~
도움이 필요하시면, DM 주시구용!ㅎㅎ

2022-07-24 12:22 UTC, daadaadaah reviewed
오늘 저녁에 시간 되시면, 마지막 작업 한번 도전해보세요🚀

2022-07-24 12:22 UTC, daadaadaah commented on src/components/Reviews.test.jsx
> +  }];
배열일 경우, 저는 2~3개정도 테스트 데이터를 사용합니당!ㅎㅎ

2022-07-24 12:22 UTC, daadaadaah commented on src/components/Reviews.test.jsx
> +  });
1. 테스트 시나리오에는 name이 렌더링 된다고 되어 있는데, 테스트 코드에는 없어요! 추가해주세요~
2.  테스트 이름을 좀더 확장성 있게 `render reivews`라고 괜찮을 것 같아요!
3. 리뷰 한개가 아닌 여러개가 보인다는 걸로 테스트 해도 괜찮을 것 같아요!

2022-07-24 12:22 UTC, daadaadaah commented on src/container/RestaurantContainer.jsx
> +    dispatch(clearReviewFields());
sendReview에서 해주는 것과 여기서 해주는 것과 어떤 차이가 있을까요?

2022-07-24 13:23 UTC, Jongveloper commented
ㅎㅎ트레이너님 항상 감사합니다!
트레이너님이 주신 피드백 덕분에 과제를 완료할 수 있었던 것 같습니다!
다음 작업부터는 트레이너님께서 말씀하신대로 작업내역을 관리해서
차분한 마음으로 과제를 진행할 수 있게끔 하겠습니다!
항상 정말 너무 많이 감사합니다!!

2022-07-25 02:35 UTC, merged