로그인 구현
CodeSoom/react-week7-assignment-1 pull request #95
Opened 2022-09-22 12:24 UTC by 0-Chan

안녕하세요..!
일단 강의는 `accessToken` 까지 듣고 구현 해놓은 상태입니다.

하지만 너무 강의를 따라가기 바빴어서.. commit이 뭉텅이가 되어 버렸는데요.

그래서 review 하시기 편하게끔 분석해서 다시 처음부터 commit을 올려보고 있습니다.
(복습 차원에서도 좋은 것 같아 시도 해보고 있습니다..!)

부족한 점 리뷰 해주시면 감사드리겠습니다! :smiley:

2022-09-22 19:38 UTC, 0-Chan commented
질문이 있습니다.... 현재 async action인 `requestLogin()` 을 테스트 하는 과정에 밤새 막혀 있습니다.ㅜ

- 테스트 fail 결과 창
![image](https://user-images.githubusercontent.com/50035753/191835196-ccb9b172-94f5-4855-97cd-5ef620676e5b.png)

검색을 통해 알아보니 `nock` 라는 HTTP 모킹 라이브러리를 사용하여 해결 해야한다는 말이 있는데 그게 맞나요..??
- - -
(지금 막힌 부분까지는 커밋이 되어있습니다!)

2022-09-23 02:15 UTC, 0-Chan commented
> 질문이 있습니다.... 현재 async action인 `requestLogin()` 을 테스트 하는 과정에 밤새 막혀 있습니다.ㅜ
> 
> * 테스트 fail 결과 창
> 검색을 통해 알아보니 `nock` 라는 HTTP 모킹 라이브러리를 사용하여 해결 해야한다는 말이 있는데 그게 맞나요..??
> 

악........... 찾았습니다.................. `__mock__` 디렉토리 내 api.js 에다가 postLogin() 을 추가 해주지 않아서 발생 했던 문제였습니다 :smiling_face_with_tear:

2022-09-23 14:07 UTC, daadaadaah requested changes
> 그래서 review 하시기 편하게끔 분석해서 다시 처음부터 commit을 올려보고 있습니다.
(복습 차원에서도 좋은 것 같아 시도 해보고 있습니다..!)

감동스런 코멘트네용😊 commit 메시지도 TDD 사이클에 맞춰 잘 진행하시고, 에러도 혼자 잘 해결하시고! 아주 멋있습니당👍 몇가지 코멘트 남겨드렸는데, 참고해서 다음 PR 날려주세요!🚀 기다리고 있을게요~

2022-09-23 14:07 UTC, daadaadaah commented on src/LoginFormContainer.jsx
> +    dispatch(requestLogin(requestLogin));
여기 오타가 있는 것 같아요!ㅎㅎ

2022-09-23 14:07 UTC, daadaadaah commented on src/LoginFormContainer.test.jsx
> +  context('when event occurs', () => {
context는 대비되는 상황에서 사용하는게 좋아요! 지금 상황에서 context를 없애도 테스트 코드를 파악하는데 문제없을 것 같아요!ㅎㅎ

2022-09-23 14:07 UTC, daadaadaah commented on src/LoginFormContainer.test.jsx
> +    it('changes email', () => {
describe-it문을 연결했을 때 자연스러운 한문장이 나오는게 좋아요!
지금 작성해주신대로 문장을 만들어보면, `LoginFormContainer가 email을 change 한다.` 라는 문장이 완성되는데, email을 change하는 것은 LoginFormContainer 아니기 때문에, `listens email change events`로 표현해주시는게 좀더 적절할 것 같아요! (아래 테스트도 마찬가지구요!ㅎㅎ)

2022-09-23 14:07 UTC, daadaadaah commented on src/reducer.test.js
> +      it('changes login field email', () => {
오직 email 만 변경된다는 의도를 드러내기 위해 `only` 를 붙여도 괜찮을 것 같아요!ㅎㅎ

2022-09-23 14:07 UTC, daadaadaah commented on src/services/__mocks__/api.js
> +}));
아샬님은 어떻게 만들어주셨는지 다시 한번 체크해봅시당!ㅎㅎ

2022-10-03 04:22 UTC, merged