레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/react-week7-assignment-1 pull request #96
Opened 2022-09-23 12:00 UTC by ChoJinmok

## :: 최근 작업 주제
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 사항 설명
- 1차 제출 (9/23)
  - 강의 모두 수강 후 코드 새롭게 작성중입니다.
  - LoginForm, LoginFormContainer

<br />

## :: 기타 질문 및 특이 사항
- 이번주는 강의에 대부분의 기능이 구현돼있어서 다시 코드 작성해보고있습니

2022-09-23 14:33 UTC, daadaadaah requested changes
이번주 강의가 꽤 길었죠😭 그래도 포기하지 않고 강의 끝까지 들으시고 다시 코드 작성해보시는 모습 너무 좋습니당!👍 다음 PR 기다리고 있을게요👊

2022-09-23 14:33 UTC, daadaadaah commented on fixtures/controls.js
> +export default controls;
`controls`보다 좀더 의도가 드러나는 단어는 없을까용? ㅎㅎ

2022-09-23 14:33 UTC, daadaadaah commented on src/LoginPage/LoginFormContainer.test.jsx
> +  context('when logged out', () => {
아래 테스트처럼 given을 사용해서 의도를 좀더 드러내주셔도 괜찮을 것 같아요!

2022-09-23 14:33 UTC, daadaadaah commented on src/services/__mocks__/api.js
> +}
이렇게 될 경우, 만약, 로그인이 실패했을 경우에도 로그인이 성공한 것처럼 'ACCESS_TOKEN'이 return되는데, 어떻게 수정하는게 좋을까요?

2022-09-24 06:24 UTC, ChoJinmok commented on src/LoginPage/LoginFormContainer.test.jsx
> +  context('when logged out', () => {
좋은 리뷰 감사합니다!~ 🙂

2022-09-24 06:27 UTC, ChoJinmok commented on fixtures/controls.js
> +export default controls;
좋은 리뷰 감사합니다 ㅎㅎ

2022-09-24 06:58 UTC, ChoJinmok commented on src/services/__mocks__/api.js
> +}
인자로 들어온 email과 password가 로그인 정보와 일치했을 때만 access token을 return해주는 걸로 수정해봤습니다!
<br />

```suggestion
export async function postLogin() {
  rconst EMAIL = 'tester@example.com';
  const PASSWORD = 'test';

  if (!(EMAIL === email && PASSWORD === password)) {
    return undefined;
  }

  return 'ACCESS_TOKEN';
}
```

2022-09-24 13:56 UTC, daadaadaah commented
진목님 작업 중이신 것 같은데, 작업 다 완료 하시구 코멘트 남겨주세요! 이후이 리뷰해드릴게요~

2022-09-24 14:32 UTC, ChoJinmok reviewed
> 진목님 작업 중이신 것 같은데, 작업 다 완료 하시구 코멘트 남겨주세요! 이후이 리뷰해드릴게요~

앗! ㅠㅠ 죄송해요 코멘트를 남긴다는게 정신 없이 코드치다보니 이렇게 됐네요... 죄송합니다 😭
기능 구현까지는 완료해서 오늘은 더 push안할 거 같습니다! 리뷰 부탁드립니다.

2022-09-25 02:33 UTC, daadaadaah requested changes
잘하셨어요! 테스트코드 작성하시는 법 많이 발전하시는 것 같아 제가 뿌듯하네용☺️
몇가지 사항만 수정해봅시당!👊

2022-09-25 02:33 UTC, daadaadaah commented on src/App.test.jsx
> +  context('when logged out', () => {
given으로 accessToken 없을 때 표현해주시면, context를 사용한 의도를 더 잘 파악할 수 있을 것 같아요!

2022-09-25 02:33 UTC, daadaadaah commented on src/LoginPage/LoginFormContainer.jsx
> +    deleteItem('accessToken');
login 기능 구현시, saveItem을 어디서 관리했는지에 대해 체크해보시고, 그곳에서 관리하는 것과 지금 컴포넌트에서 관리하는 것이 어떤 차이가 있는지 한번 생각해보세요!ㅎㅎ

2022-09-25 02:33 UTC, daadaadaah commented on src/LoginPage/LoginFormContainer.test.jsx
> +      it('doesn\'t render error message', () => {
테스트 내용과 테스트 코드 일치시켜주세요!ㅎㅎ

2022-09-25 02:33 UTC, daadaadaah commented on src/RestaurantPage/RestaurantContainer.jsx
> +  const reviews = restaurant && [...restaurant.reviews].reverse();
컴포넌트에서는 상태를 그냥 받는 걸로 하고, 상태에 필요한 처리는 상태를 관리해주는 쪽에서 해주시는 건 어떠신가요?

2022-09-25 02:33 UTC, daadaadaah commented on src/RestaurantPage/ReviewForm.test.jsx
> +  it('renders \'Send\' button', () => {
이렇게 적어주셔도 되고, `renders a button to add review` 이렇게 적어주셔도 되요! 이렇게 했을 때, 버튼의 이름이 변경되어도 이 테스트 내용은 수정할 필요가 없는 장점이 있습니당! 참고하세용ㅎㅎ

2022-09-25 02:33 UTC, daadaadaah commented on src/RestaurantsPage/RestaurantsPage.test.jsx
> +    navigate.mockClear();
mockClear를 beforeEach에서 afterEach로 변경하시 이유가 궁금합니당!ㅎㅎ

2022-09-25 02:33 UTC, daadaadaah commented on src/services/__mocks__/api.js
> +}
지금 작성해주신 방법과 아래 방법을 비교해서 보세요!
mock에서는 아래처럼 만들어주고
```js
export const postLogin = jest.fn();
```
actions.test.js 에서는 아래처럼
```js
  describe('postLogin', () => {
    context('when login is successful', () => {
      beforeEach(() => {
         // ...생략
         postLogin.mockResolvedValue('');
      });

      it('returns access token', async () => {
         // ...생략
      });
    });

    context('when login fails', () => {
      beforeEach(() => {
         // ...생략
         postLogin.mockRejectedValue(new Error('E-mail, Password를 확인해주세요.'));
      });

      it('throws error', async () => {
         // ...생략
      });
    });
  });
```

2022-09-25 07:29 UTC, ChoJinmok commented on src/App.test.jsx
> +  context('when logged out', () => {
자꾸 똑같은 실수를 하게되네용..😭

2022-09-25 08:08 UTC, ChoJinmok commented on src/LoginPage/LoginFormContainer.test.jsx
> +      it('doesn\'t render error message', () => {
앗.. 이런 실수를..🥲

2022-09-25 09:18 UTC, ChoJinmok commented on src/RestaurantPage/RestaurantContainer.jsx
> +  const reviews = restaurant && [...restaurant.reviews].reverse();
정말 그렇네요!! 이렇게 관리하는 것보다 reducer에서 관리하는 게 더 좋을 거 같아요! 좋은 리뷰 감사합니다!

2022-09-25 09:30 UTC, ChoJinmok commented on src/RestaurantPage/ReviewForm.test.jsx
> +  it('renders \'Send\' button', () => {
꿀팁 감사합니다!!~😆

2022-09-25 09:34 UTC, ChoJinmok commented on src/RestaurantsPage/RestaurantsPage.test.jsx
> +    navigate.mockClear();
저 스스로 확신 없이 고민하는 부분입니다..🥲 각 테스트 후에 mockClear해주는 것과 각 테스트 전에 mockClear하는 것중 뭐가 좋을 지 몰라서 갈팡질팡하고 있는중인 거 같아요.

2022-09-25 09:49 UTC, ChoJinmok commented on src/services/__mocks__/api.js
> +}
와.. 이렇게 간단하고 깔끔하게 mocking 해줄 수 있군요?! 너무 좋은 리뷰 감사드려요!!! 🥹

2022-09-25 11:08 UTC, ChoJinmok commented on src/LoginPage/LoginFormContainer.jsx
> +    deleteItem('accessToken');
사이드 이펙트를 미들웨어로 처리해 줘야 하는 문제인 거죠..? 사이드 이펙트를 미들웨어로 처리해 주는 이유에 대한 이해가 부족하다 보니 확실하지 않네요 😭

2022-09-25 11:10 UTC, ChoJinmok reviewed
api.js > postReview 함수의 경우에는 테스트를 진행해야할게 잘 보이지 않아서요. jest에서 더 테스트할 방법이 있을까요?

2022-09-26 02:38 UTC, daadaadaah commented on src/LoginPage/LoginFormContainer.jsx
> +    deleteItem('accessToken');
의존성 관점에서 한번 코드를 비교해보세용!ㅎㅎ

2022-09-26 02:50 UTC, daadaadaah requested changes
postReview 테스트는 지금 작성해주신대로 해도 괜찮아요! 잘하셨어요👏 이번주도 고생많으셨습니당! 다음주 마지막인데, 마지막까지 같이 힘내봐용💪

2022-09-26 02:50 UTC, daadaadaah commented on src/App.jsx
> +  });
useEffect 없이도 동작하는데, useEffect에서 해주신 이유가 궁금합니당!ㅎㅎ추가로, useEffect의 의존성 배열이 있을 때와 없을 때의 차이도 공부해보시면 좋을 것 같아요!ㅎㅎ

2022-09-26 02:50 UTC, daadaadaah commented on src/RestaurantsPage/RestaurantsPage.test.jsx
> +    navigate.mockClear();
일단은 통일감 있게만 작성주시면 될 것 같아요!
매번 똑같은 이야기지만, 결국 이런것도 다 팀 컨벤션 따라가니까요!ㅎㅎ

2022-09-26 02:50 UTC, daadaadaah commented on src/actions.js
> +    await dispatch(loadReviews({ restaurantId }));
await 오타겠죵?ㅎㅎ

2022-09-26 03:11 UTC, ChoJinmok commented on src/actions.js
> +    await dispatch(loadReviews({ restaurantId }));
앗! 테스트에 계속 에러가 떠서 발견했던건데 loadReviews 액션은 비동기로 동작하는 thunk middleware라서 clearReviewFields 액션이 먼저 실행이 돼버리더라구요! 저는 loadReviews가 완료되고 clearReviewFields를 해주고 싶어서 await를 작성해줬습니다!

2022-09-26 03:13 UTC, ChoJinmok commented on src/LoginPage/LoginFormContainer.jsx
> +    deleteItem('accessToken');
아~ 의존성 관점에서 봐야하는거군요?! 좋은 리뷰 감사합니다!!ㅎㅎ

2022-09-26 03:15 UTC, ChoJinmok commented on src/App.jsx
> +  });
다희님 리뷰 받고(결국 의존성 문제였지만요..ㅎ) deleteItem을 middleware로 처리한 것과 같이 loadItem도 side effect가 발생하는 거 같아서 useEffect로 해줬습니당..🥲 확실하지 않다보니 말씀드리는데 자신감이 없네용 ㅠㅠ

2022-10-03 04:22 UTC, merged