7주차 - 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/react-week7-assignment-1 pull request #97
Opened 2022-11-22 09:29 UTC by yxxnhx

# 목표
레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기

### 구현사항
- [ ] 로그인 form 생성하기
- [ ] 로그인 페이지 라우팅하기
- [ ] 로그인하여 accessToken 받아오기
- [ ] localStorage 활용하여 로그인 상태 유지하기
- [ ] 로그아웃 기능 구현하기
- [ ] 리뷰 추가 기능 구현하기
- [ ] 리뷰 화면에 출력하기

### 진행사항
안녕하세요 트레이너님!
현재 강의 모두 듣고 로그인부터 차근차근히 하는 중입니다.
지금까지는 로그인을 하여 accessToken까지 받아온 상황입니다. 이제 localStorage 활용해서 로그인 상태 유지하는 것, 그리고 로그아웃 기능 추가해서 만들고 리뷰를 한번 해보겠습니다!
API를 직접 이렇게 가져와서 로그인하고 추가하고 하는 것이 처음이라 많이 어렵네요..🥺
그럼 이번 한주도 잘 부탁드립니다!

2022-11-23 06:51 UTC, daadaadaah reviewed
이야기 안했는데, 스스로 given 도 쓰시고 정말 잘하셨어요!👍 
다른거 잘 구현하셨는데, 로그아웃 기능 구현할 때 localStorage도 어떤 처리 필요하지 않을까요?ㅎㅎ
다음 PR 기다리고 있을게요!🚀

2022-11-24 12:22 UTC, yxxnhx commented
# 진행사항
로그아웃 시 localStorage에 저장되었던 accessToken을 삭제할 수 있도록 기능을 추가하였습니다
그리고 리뷰들을 화면에 출력하였고 리뷰 작성 시 자동으로 loadRestaurant를 하여 입력한 리뷰가 상단에 보일 수 있도록 reverse를 이용하여 역순으로 나올 수 있게 하였습니다!

### 질문사항
![image](https://user-images.githubusercontent.com/50559373/203782835-7a12d8d8-b9d9-4897-98ca-7684fee3d59a.png)
```jsx
export default function Reviews({ reviews }) {
  if (!reviews || reviews.length === 0) {
    return <p>리뷰가 없어요!</p>;
  }
  return (
    <ul>
      {
        reviews.reverse().map((review) => (
          <li key={review.id}>
            <p>{review.name}</p>
            <p>{review.score}</p>
            <p>{review.description}</p>
          </li>
        ))
      }
    </ul>
  );
}
```
이미 Reviews에는 key가 있는데 왜 이러한 에러가 뜰까요?
로컬 크롬 콘솔창에는 위와 같은 에러가 뜨지 않습니다ㅠㅠ

![Nov-24-2022 21-21-16](https://user-images.githubusercontent.com/50559373/203783522-79dea854-ab41-4afe-b643-49a62ff112a1.gif)
그리고 리뷰를 입력할 때 자꾸 아래 리뷰들이 바뀝니다. 이게 어떠한 문제로 일어나는지를 모르겠어서 해결하지 못하고 있습니다ㅠㅠ
어디를 살펴봐야 할까요?

2022-11-25 04:12 UTC, daadaadaah requested changes
질문에 대한 답변은 리뷰에 달아놨어요! 수정하실 때 참고하세요!ㅎㅎ

2022-11-25 04:12 UTC, daadaadaah commented on src/LoginFormContainer.jsx
> +    deleteItem('accessToken');
`LoginFormContainer`가 services를 모르게 하기 위해서 accessToken 삭제 로직을 어디서 관리하는게 좋을까요?

2022-11-25 04:12 UTC, daadaadaah commented on fixtures/reviews.js
> +];
테스트 코드에 문제가 생겼을 때에는 테스트 코드에서 그 원인을 찾는게 좋아요!
지금 사용하고 계신 fixture로 사용하고 있는 reviews 데이터와 실제 구현 코드에서 사용하고 있는 review 데이터에 어떤 차이가 있을까요?

2022-11-26 06:20 UTC, yxxnhx commented on src/LoginFormContainer.jsx
> +    deleteItem('accessToken');
actions에 추가하도록 하겠습니다!

2022-11-26 06:21 UTC, yxxnhx commented on fixtures/reviews.js
> +];
앗 데이터에 id가 없어서 일어난 것이엇군요

2022-11-26 06:39 UTC, yxxnhx commented
# 진행사향
관심사 분리를 위해 services를 LoginFormContainer가 직접 알고 있지 않아도 되게 actions에 추가하였습니다.
그리고 테스트 파일에 id가 없어서 테스트에서만 에러가 뜨는 것 또한 추가하여 해결하였습니다.
리뷰 값을 입력할 때마다 계속해서 리뷰가 재랜더링 되어 삐그덕거리는 것처럼 보이는 것은 스프래드 연산자를 이용하여 받아온 리뷰를 바로 사용하지 않고 풀어서 사용할 수 있도록 하여 테스트 커버리지도 통과하였습니다.

2022-11-26 11:51 UTC, yxxnhx commented
# 진행사항
해설 강의를 듣고 입력시 input 창이 초기화 되는 기능과 레스토랑 전체 대신 리뷰만 로드될 수 있도록 수정하였습니다
그런데 그 이전까지는 e2e 테스트가 모두 통과했었는데 지금 이상하게 테스트가 깨집니다
카테고리와 레스토랑 모두 선택하면 레스토랑 목록이 나오지 않는다고 하는데 왜일까요?

2022-11-26 12:08 UTC, yxxnhx commented
## 진행사항
해설 강의를 듣고 입력시 input 창이 초기화 되는 기능과 레스토랑 전체 대신 리뷰만 로드될 수 있도록 수정하였습니다
파일들이 많아지면서 페이지별로 폴더를 정리하였는데 이 방법이 맞을까요? 아니면 조금 더 새분화해서 RestaurantsPage 같은 경우엔은 안에서 카테고리, 레스토랑, 지역을 나누어서 해주는 것이 좋을까요?

2022-11-27 08:54 UTC, daadaadaah approved these changes
> 파일들이 많아지면서 페이지별로 폴더를 정리하였는데 이 방법이 맞을까요? 아니면 조금 더 새분화해서 RestaurantPage 같은 경우엔 안에서 카테고리, 레스토랑, 지역을 나누어서 해주는 것이 좋을까요?

- 저도 폴더 및 파일 구조는 매 프로젝트 고민이 많이 되는 부분 같아요! 그래서, 저는 일단 한가지 방법으로 해보고, 그렇게 사용해보다가 불편하면 바꾸는 편입니다!ㅎㅎ페이지별로 나눠서 관리하는 것도 좋은 것 같아요! 이번주는 페이지별로 해보고, 다음주 과제 때에는 다른 방법으로 해보면서 각각의 장단점을 몸소 느껴보는게 도움이될 것 같습니다!ㅎㅎ이번주 한주도 수고 많으셨어요!👏

2022-12-01 05:13 UTC, merged