7주차 과제 - 레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/react-week7-assignment-1 pull request #98
Opened 2022-11-24 11:50 UTC by sejineeee

## 내용
안녕하세요! 이번주는 정말 PR을 빨리 생성하고 싶었지만... 강의 내용도 생각보다 어려워서 이렇게 목요일에 올렸습니다...😂
일단 강의에서 나온 부분까지 구현하였습니다.
PR 생성 이후 나머지 과제로 내준 부분을 구현할 예정입니다!!
혹시 PR 생성은 9시까지지만... 리뷰 코멘트 남기시기 전에 구현한 부분까지 올려진 상태라면 같이 봐주실 수 있으실까요?
리뷰를 받는 것이 과제 진행하는데 많은 도움이 되더라고요! 근데 제가 PR을 너무 늦게 올려서... 혹시나 가능하다면 부탁드립니다!
이번 한 주도 잘 부탁드립니다!! 🙌🏻

2022-11-24 15:18 UTC, daadaadaah commented
> 리뷰 코멘트 남기시기 전에 구현한 부분까지 올려진 상태라면 같이 봐주실 수 있으실까요?

- 오늘은 좀 피곤해서 내일 점심쯤 리뷰할 것 같아요! 계속 작업하실 수 있으시면 계속 해주세요!💪

2022-11-25 03:11 UTC, sejineeee commented
## 내용
일단 추가적으로 작업한 부분까지 올려놨습니다!!
App, RestaurantContainer 등 테스트 파일에서 reviews의 length를 읽을 수 없다는 에러로 인해서 일단 임시로 각 테스트 파일에 useSelector에 `reviews: []` 추가해줬는데, 일단 테스트를 통과하기 위해서 넣었는데 이게 맞는건지 잘 모르겠습니다ㅎㅎㅎ
조금 더 나은 방향을 고민해보도록 하겠습니다!!!

2022-11-25 04:24 UTC, daadaadaah requested changes
given 사용해보시니까 어떠셨나요?ㅎㅎ 왜 given이 필요한지에 대해 공부해보셨나요?ㅎㅎgiven을 사용했을 때 어떤 점이 좋은지에 대해서도 같이 공부해보면 좋을 것 같아요! 다음 PR 기다리고 있을게요!🚀

2022-11-25 04:24 UTC, daadaadaah commented on src/LoginForm.test.jsx
> +      <LoginForm fields={{ email, password }} onSubmit={handleSubmit} onChange={handleChange} />,
사소한 것지만 props가 3개 이상일 경우, 가로 정렬로 배치해주는게 가독성에 더 좋은 것 같아요!

2022-11-25 04:24 UTC, daadaadaah commented on src/RestaurantContainer.test.jsx
> +        );
중복을 한번 제거해봅시당!👊

2022-11-25 04:24 UTC, daadaadaah commented on src/ReviewForm.test.jsx
> +  it('renders "Send" button', () => {
어디서는 "Send" 버튼, 어디서는 "리뷰 남기기" 버튼으로 표현하시는 것 같아요! 통일성 있게 표현해봅시당!ㅎㅎ

2022-11-25 04:24 UTC, daadaadaah commented on src/Reviews.test.jsx
> +  });
expect 문이 빠졌네요?ㅎㅎ

2022-11-25 04:24 UTC, daadaadaah commented on src/ReviewsContainer.test.jsx
> +  });
expect 문이 빠졌네여?ㅎㅎ

2022-11-25 04:24 UTC, daadaadaah commented on src/TextField.test.jsx
> +    });
테스트 상황이 중복되는거 아닌가요?ㅎㅎ

2022-11-25 11:35 UTC, sejineeee commented on src/TextField.test.jsx
> +    });
아! 타입이 없을 경우에 타입이 text(기본값으로 줬음)인 input이 렌더링 되는지 확인한 거였는데 어떻게 보면 중복으로 보일 수도 있겠네요!! 수정하도록 하겠습니다!

2022-11-25 11:58 UTC, sejineeee commented
## 내용
일단 추가적으로 리뷰들이 최신순이 보이도록 reducer에서 배열을 복사한 다음 reverse 메서드를 이용하여 구현하였습니다.
아직 api 테스트랑 action에 있던 비동기 함수, storage 파일에 대한 테스트는 작업하지 않은 상태입니다! 
추가적으로 작업하여 내일 오전까지는 완료하여 푸시하도록 하겠습니다!

## 질문
1. App 컴포넌트에서 accessToken이 있을 때, dispatch가 호출되는지 테스트 하고 싶었으나, 계속 호출이 한번도 안됐다고 합니다! 이 부분을 어떤 방식으로 풀어 나가야 될 지 잘 모르겠습니다. 처음에는 `MemoryRouter`에 `initialEntries`로 인한 문제인줄 알고 `renderApp({ path = '/' } )` 이렇게도 해보고, `renderApp({ path= {} })` 이렇게도 시도해보고, `renderApp` 함수를 쓰지 않고 직접 `
`<MemoryRouter><App /></MemoryRouter>` 이렇게도 해보았는데 도저히 떠오르지 않아서 고민입니다.
<img width="410" alt="스크린샷 2022-11-25 오후 8 48 01" src="https://user-images.githubusercontent.com/86041335/203979515-35d1f3fd-417d-40d3-bdeb-7a6d712e5373.png">

2. `RestaurantContainer `에서

2022-11-26 04:40 UTC, daadaadaah requested changes
> App 컴포넌트에서 accessToken이 있을 때, dispatch가 호출되는지 테스트 하고 싶었으나, 계속 호출이 한번도 안됐다고 합니다! 이 부분을 어떤 방식으로 풀어 나가야 될 지 잘 모르겠습니다. 처음에는 MemoryRouter에 initialEntries로 인한 문제인줄 알고 renderApp({ path = '/' } ) 이렇게도 해보고, renderApp({ path= {} }) 이렇게도 시도해보고, renderApp 함수를 쓰지 않고 직접 ` 이렇게도 해보았는데 도저히 떠오르지 않아서 고민입니다.
- 그 이유는 지금 accessToken이 useSelector에서 가져오는게 아니라 localstorage에서 가져오는데, 그에 맞게 테스트 코드를 작성해주지 않으셔서 그래요! loadItem을 mocking하는 방법에 대해 공부해봅시당!ㅎㅎ


> RestaurantContainer.test 에서 리뷰 남기기 버튼을 눌렀을 때 dispatch 호출이 3번으로 된 부분이 이해가 잘 안되네요...🥺 일단 테스트 파일에서 에러가 나서, 3으로 수정한 것인데 왜 dispatch가 3번 호출되는지 잘 모르겠습니다!! ㅎㅎㅎ
- 액션들에서 로그를 찍어보면서 어떤 액션들이 dispatch 되는지, 그 로직은 어디에 있는지 확인해보시는게 좋을 것 같아요!

2022-11-26 04:40 UTC, daadaadaah commented on src/services/__mocks__/storage.js
> +const saveItem = jest.fn();
const 옆에 export 바로 붙여도 되지 않나여?ㅎㅎ

2022-11-27 12:05 UTC, sejineeee commented
## 내용
리뷰해주신대로 loadItem에 `mockImplementation`을 이용하여 테스트 하였습니다.
테스트를 할 때마다, mocking이랑 비동기 action을 테스트 하는 건 너무 어려운 거 같아요.
아샬님 강의를 보니, 비동기 action 테스트나 storage 파일 테스트, api 테스트를 다루시지 않던데, 이런 부분에 대해서 제가 혼자 공부를 하기 위해서는 어떤 자료를 참고하는 게 좋을지 추천해주시면 감사하겠습니다!

2022-11-28 07:12 UTC, daadaadaah commented
> ## 내용
> 리뷰해주신대로 `export const`를 사용하여 선언과 동시에 export 하도록 수정하였습니다. 그리고 강의를 보고, '리뷰 남기기' 버튼을 누른 다음에 input의 value가 비워지는 것을 구현하였습니다. loadItem에 `mockImplementation`을 이용하여 accessToken이 있을 경우, 없을 경우를 나누어 테스트하였습니다.
> 
> 테스트를 할 때마다, mocking이랑 비동기 action을 테스트 하는 게 너무 어렵습니다!! 🥺 아샬님 강의를 보니, 비동기 action 테스트나 storage 파일 테스트, api 테스트를 다루시지 않던데, 이런 부분에 대해서 제가 혼자 공부를 하기 위해서는 어떤 자료를 참고하는 게 좋을지 추천해주시면 감사하겠습니다!
> 
> 올린 과제에 대해서 수정하거나 이런 방향으로 작성하면 더 좋겠다 싶은 부분은 리뷰 남겨주시면 감사하겠습니다! 이번 한 주도 정말 감사합니다!! 😁

- 테스트 커버리지가 좀 아쉽지만 그래도 잘하셨어요!👏 다음주가 마지막인데, 끝까지 힘내봅시다!
- 비동기 action 테스트 관련해서 저는 [redux-mock-store](https://github.com/reduxjs/redux-mock-store) 이거 참고했었습니다!

2022-12-01 05:13 UTC, merged