week7-레스토랑 로그인 페이지 및 리뷰 작성 페이지 구현하기
CodeSoom/react-week7-assignment-1 pull request #99
Opened 2022-11-27 00:29 UTC by hyeji07

2022-11-27 09:02 UTC, daadaadaah requested changes
- 늦게 올려주셨는데 완성도 높게 과제 제출하셨네여!👍 중간에 `fixutres`를 활용할 수 있는 부분들 활용해보고, 파일 구조를 한번 변경시켜보는건 어떠신가여?ㅎㅎ

> 파이썬설치>환경변수설정>cmd 에서 httpie 설치(C:\Users\user>pip install -U httpie) 이 방법대로 했는데 잘 작동되긴 합니다. 맞는 방법인가요?? 정확한 방법이 궁금해서 질문드립니다!

- 잘 동작하면, 맞게 설치하신거예요! 잘하셨어요!👏

2022-11-27 09:02 UTC, daadaadaah commented on src/LoginForm.test.jsx
> +  it('input에 입력된 값을 확인한다', () => {
input에 입력값을 확인할 수 없고, handleChange가 호출되는 정도만 알 수 있을 것 같아요!ㅎㅎ

2022-11-27 09:23 UTC, hyeji07 commented on src/LoginForm.test.jsx
> +  it('input에 입력된 값을 확인한다', () => {
넵 test문구 변경하였습니다 !

2022-11-28 07:05 UTC, daadaadaah approved these changes
이번주도 수고 많으셨습니다!ㅎㅎ다음주가 마지막인데, 마지막까지 같이 해봐요!ㅎㅎ

2022-12-01 05:13 UTC, merged